### ISSUE TITLE
The project not work

### ISSUE THREAD

**Issue by adrix71** [symfony/demo#1005]
Hello,

I tried this project but it doesn't seem intent on working. My Apache web server is configured correctly because I tried the website_skeleton application (and many other project on my server test) and works.

How can I solve it? 

This is a screen.

![Schermata del 2019-06-30 21-37-46](https://user-images.githubusercontent.com/14064365/60401294-66d68f00-9b7f-11e9-98af-8c90e21661dc.png)

**Comment by bocharsky-bw** [comment]
Try to execute:
```bash
composer req apache-pack
```

And try again, please. It's required for running this project on Apache

**Comment by adrix71** [comment]
It's my fault. I apologize.

I read that the project is without additional configuration and I didn't think to read the documentation about how to use symfony with apache.

Now works. Thank you so much and sorry.



> Try to execute:
> 
> ```shell
> composer req apache-pack
> ```
> 
> And try again, please. It's required for running this project on Apache

It's my fault. I apologize.

I read that the project is without additional configuration and I didn't think to read the documentation about how to use symfony with apache.

Now works. Thank you so much and sorry.

**Comment by javiereguiluz** [comment]
@adrix71 Sorry for the confusion! The project requires zero-setup or configuration if you follow the recommended installation/execution process shown in the README. But, if you change the database, or the web server, etc. you'll need to make the needed changes. Luckily the solution proposed by @bocharsky-bw was easy. Closing as fixed then. Thanks!
