### ISSUE TITLE
issue when   {{ react_component('ReactApp', {'props': {} }) }}

### ISSUE THREAD

**Issue by ankitasaini-aml** [symfony/demo#1011]
An exception has been thrown during the rendering of a template ("Server bundle not found in path:

**Comment by stof** [comment]
why reporting that to the symfony/demo project ? I don't think it uses that kind of API.

**Comment by javiereguiluz** [comment]
@ankitasaini-aml we're closing this issue because we think you created it in the wrong repository ... but if you think this is not correct, please give us more information to understand why such an error could occur in the "Symfony Demo" app. Thanks.
