### ISSUE TITLE
too many errors in app.css

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1017]
```
Unknown property ‘line-break’.  Declaration dropped. app.css:18:107267
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:18:107481
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:18:107527
Unknown property ‘line-break’.  Declaration dropped. app.css:18:109062
Expected media feature name but found ‘transform-3d’. app.css:18:111399
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:18:112804
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:18:113100
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:18:113522
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:18:113755
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’. app.css:18:116044
Unknown descriptor ‘text-rendering’ in @font-face rule.  Skipped to next declaration. app.css:18:123673
Unknown descriptor ‘text-rendering’ in @font-face rule.  Skipped to next declaration. app.css:18:123893
Unknown descriptor ‘text-rendering’ in @font-face rule.  Skipped to next declaration. app.css:18:124127
Unknown descriptor ‘text-rendering’ in @font-face rule.  Skipped to next declaration.
```

**Comment by bocharsky-bw** [comment]
Hey @lxregistry 

Thank you for reporting it! Could you add more information where do you see those errors? How to reproduce them?

Cheers!

**Comment by lxregistry** [comment]
in firefox web console,
I installed like this:
npm install
npm run dev
maybe somewhere I'm wrong

**Comment by lxregistry** [comment]
{
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.10.0",
    "@symfony/webpack-encore": "^0.27.0",
    "bloodhound-js": "^1.2.3",
    "bootstrap-sass": "^3.4.1",
    "bootstrap-tagsinput": "^0.7.1",
    "bootswatch": "^3.4.1",
    "core-js": "^3.1.4",
    "eonasdan-bootstrap-datetimepicker": "^4.17.47",
    "highlight.js": "^9.15.9",
    "imports-loader": "^0.8.0",
    "jquery": "^3.4.1",
    "lato-font": "^3.0.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.1.0",
    "typeahead.js": "^0.11.1"
  },
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "dev-server": "encore dev-server",
    "dev": "encore dev",
    "watch": "encore dev --watch",
    "build": "encore production --progress"
  }
}

**Comment by javiereguiluz** [comment]
@lxregistry thanks for reporting this. These errors probably come from the theme we use or other of our dependencies. That's why we can't fix them ourselves and we must close this issue. But, if you find errors like this in our own CSS code, please consider submitting a pull request fixing them. Thanks a lot!
