### ISSUE TITLE
Forgot password - feature request

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1020]
Is there any chance to ask for this feature: Forgot password function with captcha, set new password using verification code sent by email?

**Comment by bocharsky-bw** [comment]
This feature is "in progress" to be added to the maker bundle. You can see the current implementation in https://github.com/symfony/maker-bundle/pull/359 - feel free to leave feedback or report about missing feature there.

**Comment by javiereguiluz** [comment]
Given that this will be "soon" a built-in feature provided by Symfony, let's not add it to the Demo app. In this demo application we want to showcase Symfony features ... but we must find some balance: we don't want to show all features, we don't want to show advanced features that complicate the code a lot, etc.
