### ISSUE TITLE
CommentNotificationSubscriber.php

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1022]
in CommentNotificationSubscriber.php line 55
for what this _fragment is used:

'_fragment' => 'comment_'.$comment->getId(),

?
        $linkToPost = $this->urlGenerator->generate('blog_post', [
            'slug' => $post->getSlug(),
            '_fragment' => 'comment_'.$comment->getId(),
        ], UrlGeneratorInterface::ABSOLUTE_URL);

**Comment by bocharsky-bw** [comment]
It was used to generate hash part at the end, a link like `/blog/post1#comment1` where `#comment1` is the part where `_fragment` is responsible for
