### ISSUE TITLE
Translation broken, ext-intl or symfony/polyfill-intl-messageformatter should be required in composer

### ISSUE THREAD

**Issue by vjandrea** [symfony/demo#1026]
New installation using composer create-project, when I open the demo in the browser I get:

> An exception has been thrown during the rendering of a template ("Cannot parse message translation: please install the "intl" PHP extension or the "symfony/polyfill-intl-messageformatter" package.").

Please add a requirement for ext-intl or symfony/polyfill-intl-messageformatter in composer.json. If you want I can submit a PR.

**Comment by stof** [comment]
We should add a requirement on the polyfill, so that the demo keeps working without ext-intl
