### ISSUE TITLE
Incorrect profiler paths when running in sub folder

### ISSUE THREAD

**Issue by exteon** [symfony/demo#1027]
I installed the demo app in a subfolder of document root (`/sym-demo`) w/ an apache/fpm configuration.
I configured Encore's `.setPublicPath` and built the assets. They work great.
However:
- Go to Symfony Profiler -> Configuration
- Click on any "Enabled Bundles" "Path" link
- You'll be taken to i.e. `/sym-demo/public/sym-demo/public/_profiler/open?file=vendor/symfony/twig-bundle&line=0#line0` => 404
- Notice the double `/sym-demo/public/` which is causing the issue

I'm not sure if this is a demo bug or a framework bug. While I am familiar with some of the Symfony libraries, I'm quite not used to the Symfony Framework, this is the first time installing the demo app, so I quite don't have the knowledge to debug it yet. Please forward if appropriate.

On a side, lesser note: I would also add in the documentation how to change Encore and run yarn to set up for a subfolder. I imagine there are quite a lot of people that, quite like me, don't take to a dogmatic clean install of symfony in a vhost but rather lump some pieces together to quickly see and test things on an already configured server.

**Comment by javiereguiluz** [comment]
This looks like a Symfony bug and I think it was fixed here: https://github.com/symfony/symfony/pull/32818. So, we're closing here as "fixed" and if the mentioned pull request doesn't fix this, please open an issue in the main Symfony repository (here: https://github.com/symfony/symfony/issues) so we can fix it. Thanks a lot!
