### ISSUE TITLE
Update Bootswatch and Bootstrap dependencies

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#1029]
We use bootswatch 3.* and Bootstrap 3.*.

We could upgrade bootswatch to 4.*, which in turns requires upgrading Bootstrap to 4.*. After the upgrade, the current theme (flatly) and the current styles must remain the same.

Any volunteer to help us with this? Thanks!

**Comment by abdounikarim** [comment]
Hello @javiereguiluz , i want to help you but i don't know where to start. I think i need to do this but i'm not sure : 
1. Run a `yarn install` locally
2. Update the dependencies on the `assets` directory
3. Run a `yarn build`
4. Make a commit and create a pull request.

Am I wrong ? Thanks you 😉

**Comment by stof** [comment]
you are missing "update all templates to migrate Bootstrap from 3 to 4"

**Comment by abdounikarim** [comment]
thanks you for your answer @stof . i'm going to try to solve this issue.

**Comment by javiereguiluz** [comment]
@abdounikarim thanks for taking a look at this issue!

You first need to update the bootswatch and bootstrap-sass dependencies in `package.json` to use the latest ones (4.*.*) and then you can run `yarn install`.

Then you can run `yarn encore dev --watch` and that's where you'll face some issues because some files have changed their path or name, etc.

When all issues are solved and assets build correctly, you need to check the app to see if it still looks OK or there are some minor html/css issues to fix. Thanks!

**Comment by javiereguiluz** [comment]
As @abdounikarim told me via Slack, there's a minor problem: the datepicker we use is only for Bootstrap 3. Apparently, the same creator maintains a new project at https://github.com/tempusdominus/bootstrap-4 which is compatible with Bootstrap 4. So, we're going to try that datepicker, but we'd like to listen to the community feedback about this. Thanks.

**Comment by disjfa** [comment]
I'd like to take a look when this is merged. I think more things come of this. Also i see that the variables that are in bootstrap are misused. Like to check that!

Also, should the build folder not be in the git repro? Or am i asking questions that are answered many times.

**Comment by skmedix** [comment]
Hi, can I take off this issue? Looks like #1030 is not going anywhere, and already have a lot of conflicts. If so, I can post a PR next week with upgraded all front dependencies and templates. I already have done some work on it, just let me know if I should continue.

King regards,

**Comment by javiereguiluz** [comment]
@skmedix No, please. It's true that the existing PR has some conflicts, but I'll try to fix those myself. That PR has been around for long time, so it's time to merge it (but I need to find some time for it first). Thanks for your patience!

**Comment by gabiudrescu** [comment]
@javiereguiluz can we help in some way?

**Comment by javiereguiluz** [comment]
@gabiudrescu yes! What we need to do is to compare every page in the old design and the new design. They don't have to be perfectly equal ... but they must be as similar as possible. When I checked this PR, I notice lots of significant differences and we'd like to minimize those.

So, the job to do is:

1) Compare every page before/after
2) Made the needed CSS changes/additions/removals
3) Submit those changes to this PR

Thanks!

**Comment by phpfour** [comment]
Hi @javiereguiluz 

Is someone working with the correction of PR #1030 ? If not, I can help out. 

Thanks!
