### ISSUE TITLE
Symfony 4.4 - fix deprecations?

### ISSUE THREAD

**Issue by dmaicher** [symfony/demo#1032]
I just tied Symfony 4.4-dev on the demo and saw some deprecations:

```
Testing Project Test Suite
......................................................            54 / 54 (100%)

Time: 24.18 seconds, Memory: 58.25 MB

OK (54 tests, 101 assertions)

Remaining direct deprecation notices (2)

  2x: Using the "Symfony\Component\Validator\Constraints\Length" constraint with the "min" option without setting the "allowEmptyString" one is deprecated and defaults to true. In 5.0, it will become optional and default to false.
    2x in UserControllerTest::testChangePassword from App\Tests\Controller

Remaining indirect deprecation notices (31)

  23x: Getting the container from a non-booted kernel is deprecated since Symfony 4.4.
    8x in DefaultControllerTest::tearDown from App\Tests\Controller
    6x in BlogControllerTest::tearDown from App\Tests\Controller\Admin
    4x in AddUserCommandTest::tearDown from App\Tests\Command
    3x in BlogControllerTest::tearDown from App\Tests\Controller
    2x in UserControllerTest::tearDown from App\Tests\Controller

  3x: Using the "Symfony\Component\Validator\Constraints\Length" constraint with the "min" option without setting the "allowEmptyString" one is deprecated and defaults to true. In 5.0, it will become optional and default to false.
    2x in BlogControllerTest::testAdminBackendHomePage from App\Tests\Controller\Admin
    1x in AddUserCommandTest::testCreateUserNonInteractive from App\Tests\Command

  2x: Not declaring the "Symfony\Bridge\Doctrine\DependencyInjection\AbstractDoctrineExtension::getMetadataDriverClass" method in class "Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension" is deprecated since Symfony 4.4. This method will be abstract in Symfony 5.0.
    2x in AddUserCommandTest::testCreateUserNonInteractive from App\Tests\Command

  2x: The "twig.exception_controller" configuration key has been deprecated in Symfony 4.4, set it to "null" and use "framework.error_controller" configuration key instead.
    2x in AddUserCommandTest::testCreateUserNonInteractive from App\Tests\Command

  1x: Loading the file "../src/Controller/" from the global resource directory "/var/www/symfony-demo/src" is deprecated since Symfony 4.4 and will be removed in 5.0.
    1x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Admin

Other deprecation notices (50)

  33x: The "twig.exception_listener" service is deprecated since Symfony 4.4.
    4x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Admin
    4x in DefaultControllerTest::testSecureUrls from App\Tests\Controller
    4x in BlogControllerTest::testNewComment from App\Tests\Controller
    3x in DefaultControllerTest::testPublicUrls from App\Tests\Controller
    2x in UserControllerTest::testEditUser from App\Tests\Controller
    2x in UserControllerTest::testAccessDeniedForAnonymousUsers from App\Tests\Controller
    2x in UserControllerTest::testChangePassword from App\Tests\Controller
    2x in BlogControllerTest::testAdminDeletePost from App\Tests\Controller\Admin
    2x in BlogControllerTest::testAdminEditPost from App\Tests\Controller\Admin
    2x in BlogControllerTest::testAdminNewPost from App\Tests\Controller\Admin
    1x in BlogControllerTest::testIndex from App\Tests\Controller
    1x in BlogControllerTest::testAjaxSearch from App\Tests\Controller
    1x in DefaultControllerTest::testPublicBlogPost from App\Tests\Controller
    1x in BlogControllerTest::testAdminShowPost from App\Tests\Controller\Admin
    1x in BlogControllerTest::testAdminBackendHomePage from App\Tests\Controller\Admin
    1x in BlogControllerTest::testRss from App\Tests\Controller

  4x: The "twig.controller.exception" service is deprecated since Symfony 4.4.
    4x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Admin

  4x: The template "@Twig/layout.html.twig" is deprecated since Symfony 4.4, will be removed in 5.0. ("@Twig/layout.html.twig" at line 1).
    4x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Admin

  4x: The template "@Twig/exception.css.twig" is deprecated since Symfony 4.4, will be removed in 5.0. ("@Twig/exception.css.twig" at line 1).
    4x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Admin

  4x: The template "@Twig/base_js.html.twig" is deprecated since Symfony 4.4, will be removed in 5.0. ("@Twig/base_js.html.twig" at line 1).
    4x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Admin

  1x: The "Symfony\Bundle\TwigBundle\Controller\ExceptionController" class is deprecated since Symfony 4.4, use "Symfony\Component\HttpKernel\Controller\ErrorController" instead.
    1x in BlogControllerTest::testAccessDeniedForRegularUsers from App\Tests\Controller\Adm

**Comment by stof** [comment]
Well, the demo is still using Symfony 4.3 for now. If you are running a `composer update` rather than a `composer install`, it is totally expected that you get such deprecations, as the upgrade work has not been done yet.

**Comment by dmaicher** [comment]
@stof yes I meant we could probably start fixing deprecations already before the new 4.4 release? Or we can also wait until the release and fix it all together? In that case I could close the issue for now :blush:

**Comment by dmaicher** [comment]
Probably makes sense to fix all of them after the release

**Comment by redkenusa** [comment]
I have some deprecations 

23:33:38 | n/a | The "Symfony\Component\HttpKernel\EventListener\ExceptionListener" class is deprecated since Symfony 4.4, use "ErrorListener" instead.Show context    Show trace
-- | -- | --
23:33:38 | n/a | Passing more than one argument to Symfony\Component\HttpKernel\Config\FileLocator::__construct is deprecated since Symfony 4.4 and will be removed in 5.0.Show context    Show trace
23:33:38 | n/a | Loading the file "../../src/Controller/" from the global resource directory "..\src" is deprecated since Symfony 4.4 and will be removed in 5.0.Show context    Show trace
23:33:38 | n/a | Loading the file "../../src/Controller/" from the global resource directory "..\src/Resources" is deprecated since Symfony 4.4 and will be removed in 5.0.Show context    Show trace

How I can fix that, is when update to 4.4 thank you so much

Keiler Nunez
www.kencomputerspro.com

**Comment by qg0** [comment]
So, what the solution for this "  1x: The "twig.exception_listener" service is deprecated since Symfony 4.4."?
As I understand "composer update" doesn't work properly yet.
The installation from scratch (composer install) doesn't help.

**Comment by dsentker** [comment]
I have got the same issues. Installed SF 4.3, just upgraded to 4.4 and got the same deprecation logs. All my composer.json version constraints are set to ^4.4.

* [2019-12-04 22:14:44] php.INFO: User Deprecated: The "twig.exception_listener" service is deprecated since Symfony 4.4. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"twig.exception_listener\" service is deprecated since Symfony 4.4. at .../var/cache/prod/Container0xh3nrp/getTwig_ExceptionListenerService.php:9)"} []
* [2019-12-04 22:14:44] php.INFO: User Deprecated: The "Symfony\Component\HttpKernel\EventListener\ExceptionListener" class is deprecated since Symfony 4.4, use "ErrorListener" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener\" class is deprecated since Symfony 4.4, use \"ErrorListener\" instead. at .../vendor/symfony/http-kernel/EventListener/ExceptionListener.php:25)"} []

**Comment by dmaicher** [comment]
Maybe this helps?
https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#twigbundle

If you cannot fix your deprecations then please open an issue here: https://github.com/symfony/symfony

**Comment by jfcherng** [comment]
Looks more like this https://github.com/symfony/symfony/issues/34556.

**Comment by redkenusa** [comment]
I already fix the issue, I copy src, templates, public the files use on my proyect on symfony 5, and Install with composer the bundle I use and is running perfect

**Comment by dsentker** [comment]
I used the line `exception_controller: null` and now it seems to work - no more deprecation notices.

**Comment by rickerd** [comment]
The old way of handling doesn't work anymore in Symfony 4.4.
The class had some information about this tread. Where to put the correct files and parameters.

[Here's the info](https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#twigbundle)

**Before:**
_config/packages/twig.yaml_
```
twig:
    exception_controller: 'App\Controller\MyExceptionController'
    ...
```

**After:**
_config/packages/twig.yaml_
```
twig:
    exception_controller: null
    ...
```

**Before:**
_config/routes/dev/twig.yaml_
```
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    ...
```

**After:**
_config/routes/dev/twig.yaml_
```
_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    ...
```

**Comment by ashimolin** [comment]
> Maybe this helps?
> https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#twigbundle

Outdated link, correct link now is https://github.com/symfony/symfony/blob/4.4/CHANGELOG-4.4.md
