### ISSUE TITLE
Need to require ext-mbstring ?

### ISSUE THREAD

**Issue by mazarini** [symfony/demo#1034]
Hi,

Since 7.1, erusev/parsedown require ext-mbstring and before 7.2 eresus/markdown have a vulnerabily due to markdown.

I made a test with symfony/demo and receive a message from security-check when require an extra package and when I try to update because of erusev/parsedown

Install php-mbstring solve the problem because without 7.0 is installed.

**Comment by javiereguiluz** [comment]
Sorry we didn't reply to this on time. I've checked the project and I don't see any security vulnerabilities in the latest version. So, I'm closing this as "probably fixed". Please, tell me if this is not true so we can reopen it.

Also, not strictly related to this, but in #1055 we migrated this project to use the String component, so hopefully we can do anything related to strings without using the mbstring extension.
