### ISSUE TITLE
Replace Swiftmailer with Mailer Component

### ISSUE THREAD

**Issue by ker0x** [symfony/demo#1036]
Currently this project use Swiftmailer to send email, for now only when a comment is created (however, delivery is disabled by default).

As a demo application to demonstrate Symfony capabilities, I think it will make sense to switch to the Mailer Component introduce in 4.3. What do you think ?

**Comment by noniagriconomie** [comment]
Maybe with 4.4 soon, some other code/best practice etc will need to be improved

**Comment by bocharsky-bw** [comment]
> Maybe with 4.4 soon, some other code/best practice etc will need to be improved

This sounds like a separate from Mailer PR to me

**Comment by noniagriconomie** [comment]
yes agreed :)
