### ISSUE TITLE
Login fails after fixture:load. Appears to be related to 'Auto' vs 'Bcrypt' in config.

### ISSUE THREAD

**Issue by icircletech** [symfony/demo#1040]
Here is what I have found when installing the demo app. (Symfony Version 4.3.5 / PHP 7.1.23)

Upon initial install, everything works great. I can login and I can log out without issue.

If I run doctrine:fixtures:load, I can no longer login afterwards.

I have found that running doctrine:query:sql before the doctrine:fixture:load shows Bcrypt encrypted passwords, and after doctrine:fixtures:load the passwords are Argon2 encrypted. 

For a workaround, I have changed the config in the security.yaml from auto to bcrypt. If I rerun the doctrine:fixtures:load again after changing to bcrypt, I can then login again.

I noticed that bcrypt was showing up in the debugger as deprecated, so i figured I should submit an issue here.

**Comment by abdounikarim** [comment]
Hello @icircletech , i just installed the Symfony Demo and the version is 4.3.3. The authentication works fine.

I just run a `composer update` and Symfony is now in 4.3.5. And i still don't have any authentication problem. 

When you installed Symfony, you ran the `symfony new --demo my_project` command ?

Cheers 😉

**Comment by icircletech** [comment]
Hello @abdounikarim, thank you for the reply 😉.  I installed using the `symfony new my_project_name --demo` in CLI. 

Did you run `./bin/console doctrine:fixtures:load` in CLI?   This command is what breaks my authentication.

**Comment by abdounikarim** [comment]
@icircletech yes and i don't have any problem.

**Comment by javiereguiluz** [comment]
Let's close this old issue because we haven't received any similar feedback about this and authentication seem to be working as expected. Thanks.
