### ISSUE TITLE
6 packages have known vulnerabilities.

### ISSUE THREAD

**Issue by makzef** [symfony/demo#1047]
Hi)
Cannot install demo application because it brings errors when installing symfony (v. 4.3.3). 
Error: Script security-checker security:check returned with error code 1. 6 packages have known vulnerabilities. 
Can someone fix it, and upgrade to symfony 4.4 at least?

**Comment by abdounikarim** [comment]
Hello, this issue is similar, right ? 
https://github.com/symfony/demo/issues/1044

**Comment by makzef** [comment]
Yeah, I got the exactly error like in that issue. I tried to install it in different ways. Even tried to clone a project, and ran `composer.install` Had the same error...

**Comment by abdounikarim** [comment]
Can you close this issue ? Because the other is already opened ? Thanks 😉
