### ISSUE TITLE
make it working with symfony 4.4 , twig 3.0 and Bootstrap v4.3.1

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1048]
is there any chance to fix depreciations in this demo and make it working with symfony 4.4 , twig 3.0 and Bootstrap v4.3.1

to remove all warnings

**Comment by noniagriconomie** [comment]
There is a PR for 5.0
I think it will improve a lot the demo :)

But for maintainers, the readme tell as a requirement PHP 7.1, but when clicking on the link after, the symfony doc said 7.2.9

Maybe we can upgrade the version no?

**Comment by javiereguiluz** [comment]
Closing as fixed because the app has been upgraded to Symfony 5 (#1039), Twig 3 (#1049) and there's a pending PR to upgrade it to Bootstrap 4 (#1030).
