### ISSUE TITLE
Paginator

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1075]
in some version this package 'white-october/pagerfanta-bundle' was replaced with custom code, but it is not work correctly.
if you have 20 pages it show this
Previous 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 Next
if you have 100 it will show all 100 but it should show like in google style
Previous 1 2 3 4 5 6 7 8 9 10 Next  and you click Next it should show next 11..20
Previous 11 12 13 14 15 16 17 18 19 20 Next

**Comment by lxregistry** [comment]
any comments about this issue?,
just set private const PAGE_SIZE = 1; to see how it looks

**Comment by bocharsky-bw** [comment]
Most probably it just was not implemented because we didn't have enough results for noticing this problem. If so, I think it would be good to implement this

**Comment by lxregistry** [comment]
any chance to resolve this? or maybe to use another bundle like BabDevPagerfantaBundle ?
