### ISSUE TITLE
Change directory for ChangePasswordType

### ISSUE THREAD

**Issue by seb-jean** [symfony/demo#1083]
Hi :),

I think the Form ChangePasswordType should be placed in src/Form/ChangePasswordType.php instead of src/Form/Type/ChangePasswordType.php

**Comment by ker0x** [comment]
Hello @seb-jean,

This is something that was already discussed when creating the feature, here is the reason why it's in `src/Form/Type/` https://github.com/symfony/demo/pull/834#issuecomment-424841624

**Comment by cybernet** [comment]
should this be closed ?

**Comment by javiereguiluz** [comment]
Yes, storing form types in the `Type/` subdirectory is intended because we want to recommend doing that. So, let's close this. Thanks.
