### ISSUE TITLE
Use singular namespaces

### ISSUE THREAD

**Issue by BafS** [symfony/demo#1092]
The demo has singular namespaces except for DataFixtures, Events and Migrations.

The documentation uses singular form, for example `App\Event\...` (https://symfony.com/doc/current/event_dispatcher.html), I think it would be good to be in-pair with the doc and the conventions.

What do you think ?

**Comment by javiereguiluz** [comment]
Yes ... using `Event` in singular would be in sync with the docs (the other namespaces in plural are OK and we can keep them). Would you be able to make a pull request to fix this? Thanks!
