### ISSUE TITLE
Backend - doesn't access (AccessDeniedHttpException HTTP 403 Forbidden)

### ISSUE THREAD

**Issue by Mausino** [symfony/demo#1101]
I installed the brrand new symfony/demo.. 

if i run this demo by command: $ symfony serve 

I am getting the Access Denied (403) issue if i click from home  ("/") page to Backend button which get me on page ("/en/admin/post"/)  -> the frontend works fine :)

If i run this demo by: $ php -S localhost:8000 -t public/ **it's working without any problem**

![symf_err_1](https://user-images.githubusercontent.com/5773777/80357376-346af080-887b-11ea-96b3-fdfee029c283.png)
![symf_err_2](https://user-images.githubusercontent.com/5773777/80357383-38970e00-887b-11ea-8c1d-e7c338d149c2.png)

**Comment by bocharsky-bw** [comment]
I think it was done on purpose to show that regular user (as I see you're logged in as `john_user` who does not have access to admin part of the app) are not granted to see the backend

**Comment by Mausino** [comment]
@bocharsky-bw 

maybe i din't exacly described the main view on problem

Why backend on command works diffrently

$ php -S localhost:8000 -t public/   - works without any issue 
$ bin/console server:run  - admin part has issue.... if i want to go backend
$ symfony serve - admin part has issue... if i want to go backend

This is why i wondering... why on php 7.4 on my local php server is working but not on symfony CLI

**Comment by bocharsky-bw** [comment]
Please, make sure you're logged in as an admin user, `john_user` is not an admin, use `jane_admin` username instead, and you won't see that error. Most probably you're logged in as `jane_admin` on your local PHP webserver if you say you don't see this error. Log out and log in again as `jane_admin` :)

The error you see on the screenshot above means that not admin users do not have access to the admin panel, that's it.
