### ISSUE TITLE
Bug: there's no setException method in ExceptionEvent

### ISSUE THREAD

**Issue by brentybh** [symfony/demo#1115]
https://github.com/symfony/demo/blob/7e49b6414ab7d143b9aba9354f2c1c3760b38cd4/src/EventSubscriber/CheckRequirementsSubscriber.php#L88

Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "setException" of class "Symfony\Component\HttpKernel\Event\ExceptionEvent"." at D:\home\site\wwwroot\src\EventSubscriber\CheckRequirementsSubscriber.php line 88

**Comment by xabbuh** [comment]
see #1116
