### ISSUE TITLE
Pagination does not preserve filter by tag

### ISSUE THREAD

**Issue by jkufner** [symfony/demo#1135]
Start the demo and go to `http://localhost:8000/en/blog/?tag=consectetur`, then click "Next →" button in the paginator.

The next URL should be `http://localhost:8000/en/blog/page/2?tag=consectetur`, but it is `http://localhost:8000/en/blog/page/2` instead — the `?tag=consectetur` is missing.

**Comment by javiereguiluz** [comment]
Thanks for reporting ... and fixing this in #1136.
