### ISSUE TITLE
UserRepository

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1148]
Argument 1 passed to App\Repository\UserRepository::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /var/www/vhosts/...............

**Comment by lxregistry** [comment]
`-` use Doctrine\Common\Persistence\ManagerRegistry;
`+` use Doctrine\Persistence\ManagerRegistry;

**Comment by yceruto** [comment]
Up for a PR solving https://github.com/symfony/demo/issues/1149 and https://github.com/symfony/demo/issues/1147 too?
