### ISSUE TITLE
Paginator.php

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1159]
Paginator do not work properly
just set

    private const PAGE_SIZE = 2;

and you will see result

seems this symfony demo is abandoned,

**Comment by stof** [comment]
what do you mean by "does not work properly" ? what is happening ?

**Comment by javiereguiluz** [comment]
@lxregistry thanks for reporting this error. It's being fixed in #1126.

Also -> this project is NOT abandoned. Sometimes it takes us a bit to review/merge things, but that's OK.
