### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1164]
I think this pagination still do not work properly in 1.6.2 version
if you have 1000 posts and you will set  
public const PAGE_SIZE = 2;

then you will have on page 500 links, this is not normal, maybe it require some extra functions in twig code

![paginator](https://user-images.githubusercontent.com/32699348/95467482-2f5fb080-0986-11eb-8a7e-7b36079e8733.jpg)

it should look like this

![google-page](https://user-images.githubusercontent.com/32699348/95468358-186d8e00-0987-11eb-9791-7e4953e56bdd.jpg)

**Comment by stof** [comment]
Well, if you want more advanced pagination UI (skipping some links for instance), using a library like Pagerfanta (which deals with that buit-in) might make sense rather than using simpler pagination implementation (or reimplementing the library in the project).

**Comment by lxregistry** [comment]
> Pagerfanta

is abandoned

**Comment by lxregistry** [comment]
`{% if paginator.lastPage > 1 %}
    {% set nearbyPagesLimit = 5 %}
    <div class="pagination-container">
        <ul class="pagination">
            <li class="page-item{% if paginator.currentPage == 1 %} disabled{% endif %}">
                <a class="btn btn-common" href="{{ path(route_name, {'page': paginator.previousPage}|merge(app.request.query.all())) }}">
                    <i class="lni-chevron-left"></i>
                    <span class="d-lg-inline d-none">Previous</span>
                </a>
            </li>
            {% for i in 1..paginator.lastPage %}
                {% if 0 == (paginator.currentPage - nearbyPagesLimit) - loop.index %} {# dot before #}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% elseif 0 == (paginator.currentPage + nearbyPagesLimit) - loop.index %} {# dot after #}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% elseif 0 < (paginator.currentPage - nearbyPagesLimit) - loop.index %} {# hide all before #}
                {% elseif 0 > (paginator.currentPage + nearbyPagesLimit) - loop.index %} {# hide all after #}
                {% else %}
                    <li class="page-item{% if paginator.currentPage == loop.index %} active{% endif %}">
                        <a class="page-link" href="{{ path(route_name, {'page': loop.index}|merge(app.request.query.all())) }}">
                            {{ loop.index }}
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="page-item{% if paginator.currentPage == paginator.lastPage %} disabled{% endif %}">
                <a class="btn btn-common" href="{{ path(route_name, {'page': paginator.nextPage}|merge(app.request.query.all())) }}">
                    <span class="d-lg-inline d-none">Next</span>
                    <i class="lni-chevron-right"></i>
                </a>
            </li>
        </ul>
    </div>
{% endif %}`

**Comment by stof** [comment]
@lxregistry Pagerfanta is *not* abandoned. A new maintainer has been found.

**Comment by lxregistry** [comment]
> 
> 
> @lxregistry Pagerfanta is _not_ abandoned. A new maintainer has been found.

latest release v2.1.3 Jul 17, 2019

**Comment by javiereguiluz** [comment]
@lxregistry you are right that the pagination of this application is not prepared for having hundreds of blog posts ... but it's OK because this is a demo application, so it's realistic but not completely real. We can take some shortcuts to focus on the important things (showing how to develop an app with Symfony) instead of polishing all details. Thanks for understanding!
