### ISSUE TITLE
Install demo - error

### ISSUE THREAD

**Issue by PetrovNV** [symfony/demo#1172]
Installing twig/markdown-extra (v3.0.5): Extracting archive
    0 [>---------------------------]    0 [>---------------------------]Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
86 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> symfony-cmd
'symfony-cmd' is not recognized as an internal or external command,
operable program or batch file.
Script symfony-cmd handling the auto-scripts event returned with error code 1
Script @auto-scripts was called via post-install-cmd

**Comment by xabbuh** [comment]
Which command did you execute? Can you show the full output that you got when doing so?

**Comment by PetrovNV** [comment]
> Which command did you execute? Can you show the full output that you got when doing so?

C:\DEV\PhpstormProjects\Symfony>symfony new --demo demo
* Creating a new Symfony Demo project with Composer
  (running C:\Users\petro\composer\composer.phar create-project symfony/symfony-demo C:\DEV\PhpstormProjects\Symfony\demo)

exit status 1
Creating a "symfony/symfony-demo" project at "./demo"
Installing symfony/symfony-demo (v1.6.2)
  - Installing symfony/symfony-demo (v1.6.2): Extracting archive
Created project in C:\DEV\PhpstormProjects\Symfony\demo
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 110 installs, 0 updates, 0 removals
    0 [>---------------------------]    0 [>---------------------------]  - Installing composer/package-versions-deprecated (1.11.99): Extracting archive
  - Installing symfony/flex (v1.9.6): Extracting archive
The "symfony/flex" plugin was skipped because it is not compatible with Composer 2+. Make sure to update it to version 1.9.8 or greater.
  - Installing symfony/polyfill-php80 (v1.18.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/routing (v5.1.7): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.18.1): Extracting archive
  - Installing symfony/polyfill-php73 (v1.18.1): Extracting archive
  - Installing symfony/polyfill-ctype (v1.18.1): Extracting archive
  - Installing symfony/http-foundation (v5.1.7): Extracting archive
  - Installing symfony/http-client-contracts (v2.2.0): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v2.2.0): Extracting archive
  - Installing symfony/event-dispatcher (v5.1.7): Extracting archive
  - Installing symfony/var-dumper (v5.1.7): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing symfony/error-handler (v5.1.7): Extracting archive
  - Installing symfony/http-kernel (v5.1.7): Extracting archive
  - Installing symfony/finder (v5.1.7): Extracting archive
  - Installing symfony/filesystem (v5.1.7): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing symfony/service-contracts (v2.2.0): Extracting archive
  - Installing symfony/dependency-injection (v5.1.7): Extracting archive
  - Installing symfony/config (v5.1.7): Extracting archive
  - Installing symfony/var-exporter (v5.1.7): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing symfony/cache-contracts (v2.2.0): Extracting archive
  - Installing symfony/cache (v5.1.7): Extracting archive
  - Installing symfony/framework-bundle (v5.1.7): Extracting archive
  - Installing doctrine/lexer (1.2.1): Extracting archive
  - Installing doctrine/annotations (1.10.4): Extracting archive
  - Installing doctrine/reflection (1.2.1): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
  - Installing doctrine/collections (1.6.7): Extracting archive
  - Installing doctrine/cache (1.10.2): Extracting archive
  - Installing doctrine/persistence (2.0.0): Extracting archive
  - Installing symfony/doctrine-bridge (v5.1.7): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.18.1): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.18.1): Extracting archive
  - Installing symfony/string (v5.1.7): Extracting archive
  - Installing symfony/console (v5.1.7): Extracting archive
  - Installing doctrine/sql-formatter (1.1.1): Extracting archive
  - Installing doctrine/dbal (2.10.4): Extracting archive
  - Installing doctrine/doctrine-bundle (2.1.2): Extracting archive
  - Installing dama/doctrine-test-bundle (v6.3.3): Extracting archive
  - Installing doctrine/instantiator (1.3.1): Extracting archive
  - Installing doctrine/inflector (1.4.3): Extracting archive
  - Installing doctrine/common (3.0.2): Extracting archive
  - Installing doctrine/orm (v2.7.3): Extracting archive
  - Installing doctrine/data-fixtures (1.4.4): Extracting archive
  - Installing doctrine/doctrine-fixtures-bundle (3.3.2): Extracting archive
  - Installing symfony/stopwatch (v5.1.7): Extracting archive
  - Installing zendframework/zend-eventmanager (3.2.1): Extracting archive
  - Installing zendframework/zend-code (3.4.1): Extracting archive
  - Installing ocramius/proxy-manager (2.2.3): Extracting archive
  - Installing doctrine/migrations (3.0.1): Extracting archive
  - Installing doctrine/doctrine-migrations-bundle (3.0.1): Extracting archive
  - Installing erusev/parsedown (1.7.4): Extracting archive
  - Installing symfony/process (v5.1.7): Extracting archive
  - Installing symfony/options-resolver (v5.1.7): Extracting archive
  - Installing php-cs-fixer/diff (v2.0.1): Extracting archive
  - Installing composer/xdebug-handler (1.4.3): Extracting archive
  - Installing composer/semver (3.2.1): Extracting archive
  - Installing friendsofphp/php-cs-fixer (3.0.x-dev 236fb50): Extracting archive
  - Installing league/uri-parser (1.4.1): Extracting archive
  - Installing masterminds/html5 (2.7.4): Extracting archive
  - Installing sensio/framework-extra-bundle (v5.6.1): Extracting archive
  - Installing symfony/apache-pack (v1.0.1): Extracting archive
  - Installing symfony/dom-crawler (v5.1.7): Extracting archive
  - Installing symfony/browser-kit (v5.1.7): Extracting archive
  - Installing symfony/css-selector (v5.1.7): Extracting archive
  - Installing twig/twig (v3.0.5): Extracting archive
  - Installing symfony/translation-contracts (v2.3.0): Extracting archive
  - Installing symfony/twig-bridge (v5.1.7): Extracting archive
  - Installing symfony/debug-bundle (v5.1.7): Extracting archive
  - Installing symfony/dotenv (v5.1.7): Extracting archive
  - Installing symfony/expression-language (v5.1.7): Extracting archive
  - Installing symfony/property-info (v5.1.7): Extracting archive
  - Installing symfony/property-access (v5.1.7): Extracting archive
  - Installing symfony/intl (v5.1.7): Extracting archive
  - Installing symfony/polyfill-intl-icu (v1.18.1): Extracting archive
  - Installing symfony/form (v5.1.7): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.18.1): Extracting archive
  - Installing symfony/mime (v5.1.7): Extracting archive
  - Installing egulias/email-validator (2.1.22): Extracting archive
  - Installing symfony/mailer (v5.1.7): Extracting archive
  - Installing nikic/php-parser (v4.10.2): Extracting archive
  - Installing symfony/maker-bundle (v1.21.1): Extracting archive
  - Installing monolog/monolog (2.1.1): Extracting archive
  - Installing symfony/monolog-bridge (v5.1.7): Extracting archive
  - Installing symfony/monolog-bundle (v3.6.0): Extracting archive
  - Installing symfony/phpunit-bridge (v5.1.7): Extracting archive
  - Installing symfony/polyfill-intl-messageformatter (v1.18.1): Extracting archive
  - Installing symfony/security-core (v5.1.7): Extracting archive
  - Installing symfony/security-http (v5.1.7): Extracting archive
  - Installing symfony/security-guard (v5.1.7): Extracting archive
  - Installing symfony/security-csrf (v5.1.7): Extracting archive
  - Installing symfony/security-bundle (v5.1.7): Extracting archive
  - Installing symfony/translation (v5.1.7): Extracting archive
  - Installing symfony/twig-bundle (v5.1.7): Extracting archive
  - Installing twig/extra-bundle (v3.0.5): Extracting archive
  - Installing symfony/twig-pack (v1.0.0): Extracting archive
  - Installing symfony/validator (v5.1.7): Extracting archive
  - Installing symfony/web-profiler-bundle (v5.1.7): Extracting archive
  - Installing symfony/asset (v5.1.7): Extracting archive
  - Installing symfony/webpack-encore-bundle (v1.7.3): Extracting archive
  - Installing symfony/yaml (v5.1.7): Extracting archive
  - Installing tgalopin/html-sanitizer (1.4.0): Extracting archive
  - Installing tgalopin/html-sanitizer-bundle (1.2.0): Extracting archive
  - Installing twig/intl-extra (v3.0.5): Extracting archive
  - Installing twig/markdown-extra (v3.0.5): Extracting archive
    0 [>---------------------------]    0 [>---------------------------]Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
86 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> symfony-cmd
'symfony-cmd' is not recognized as an internal or external command,
operable program or batch file.
Script symfony-cmd handling the auto-scripts event returned with error code 1
Script @auto-scripts was called via post-install-cmd

C:\DEV\PhpstormProjects\Symfony>

**Comment by stof** [comment]
That's because of the warning here:

> The "symfony/flex" plugin was skipped because it is not compatible with Composer 2+. Make sure to update it to version 1.9.8 or greater.

@javiereguiluz it would be great to upgrade symfony/flex in the demo to a version compatible with Composer 2 and make a new release of the demo, given that Composer 2 is now the stable release.
