### ISSUE TITLE
No vendor directory and autoload.php

### ISSUE THREAD

**Issue by K2AAE** [symfony/demo#1178]
New install from today, had to add php7.3-fpm to server, tested ok, installed demo and get:
PHP Warning:  require(/home/kevin/demo_project/vendor/autoload.php): failed to open stream: 
There is no vendor directory. PHP-FPM shows it is working but broswer can not connect to the server...

**Comment by xabbuh** [comment]
How did you install the demo application?

**Comment by rahimlijeyhun** [comment]
Try just do this in your project directory: 
![composer_instal](https://user-images.githubusercontent.com/42419692/103635869-6de71600-4f49-11eb-8296-d438a36d6b70.png)

**Comment by javiereguiluz** [comment]
Closing because it looks like an installation issue instead of a project issue. Running "composer install" should fix this problem by installing the required dependencies. Thanks!
