### ISSUE TITLE
Undefined constant 'T_NAME_QUALIFIED'

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1181]
installed today this demo with symfony 5.2 "doctrine/orm": "^2.8", and php 8,

received this error,
Undefined constant 'T_NAME_QUALIFIED'
 in /vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/TokenParser.php (line 187) 

```
     {
        $name = '';
        while (
            ($token = $this->next()) && ($token[0] === T_STRING || $token[0] === T_NS_SEPARATOR || (
            PHP_VERSION_ID >= 80000 &&
            ($token[0] === T_NAME_QUALIFIED || $token[0] === T_NAME_FULLY_QUALIFIED)
            ))
        ) {
            $name .= $token[1];
        }
```

any help will be apreciated

**Comment by stof** [comment]
the code path using the `T_NAME_QUALIFIED` runs only if the condition `PHP_VERSION_ID >= 80000` is true. That's really weird, as `T_NAME_QUALIFIED` is defined on PHP 8
