### ISSUE TITLE
Errors on installation on php8

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [symfony/demo#1204]
Hi.
Local web serwer (OpenServer_5_3_8) on Win 8.1, PHP8, all extensions intalled (Ctype, iconv, JSON, PCRE, Session, SimpleXML,Tokenizer, sqlite)

An attempt to run the command "symfony new . --demo" fails:

![изображение](https://user-images.githubusercontent.com/1030328/113885213-56c5f780-97c8-11eb-84e9-73166ffcc897.png)
![изображение](https://user-images.githubusercontent.com/1030328/113885249-5ded0580-97c8-11eb-945e-fd0ae8f08e94.png)

And other errors from web path:
![изображение](https://user-images.githubusercontent.com/1030328/113885792-cdfb8b80-97c8-11eb-8fa4-7658245776cc.png)

Why?

**Comment by stof** [comment]
IIRC, `symfony new --demo` uses the released version of the demo. Proper support for PHP 8 was added after the last release and is only in the dev version for now.

**Comment by Vasiliy-Makogon** [comment]
rosier, do I understand correctly that I cannot install a demo on PHP8 until this pull request is approved?

well, what doing this commit? - [Allow PHP 8 to run the project] (https://github.com/symfony/demo/commit/782b08d3ee6360a75422a87a7f80560843757699)

**Comment by Vasiliy-Makogon** [comment]
do I understand correctly that I cannot install a demo on PHP8 until this pull request is approved?

well, what doing this commit? - [Allow PHP 8 to run the project] (https://github.com/symfony/demo/commit/782b08d3ee6360a75422a87a7f80560843757699)

**Comment by rosier** [comment]
At moment `symfony new --demo` and `composer create-project symfony/symfony-demo` pick an older version that doesn't work on PHP 8. The PR #1194 plus a new release should fix that.

For now you can try the following to install the demo
```
git clone https://github.com/symfony/demo.git demo
cd demo
composer install
```
and to start the demo
```
symfony serve -d
symfony open:local
```

**Comment by vinobstin** [comment]
> Hi.
> Local web serwer (OpenServer_5_3_8) on Win 8.1, PHP8, all extensions intalled (Ctype, iconv, JSON, PCRE, Session, SimpleXML,Tokenizer, sqlite)
> 
> An attempt to run the command "symfony new . --demo" fails:
> 
> ![изображение](https://user-images.githubusercontent.com/1030328/113885213-56c5f780-97c8-11eb-84e9-73166ffcc897.png)
> ![изображение](https://user-images.githubusercontent.com/1030328/113885249-5ded0580-97c8-11eb-945e-fd0ae8f08e94.png)
> 
> And other errors from web path:
> ![изображение](https://user-images.githubusercontent.com/1030328/113885792-cdfb8b80-97c8-11eb-8fa4-7658245776cc.png)
> 
> Why? problems with downloading from another web (expetionproblems with downloading from another web (expetion)

**Comment by vinobstin** [comment]
directly out of the web when I have a download from soul browswer

**Comment by javiereguiluz** [comment]
Let's close this old issue because we haven't received similar reports from other users. Thanks.
