### ISSUE TITLE
sccs files blocked

### ISSUE THREAD

**Issue by Alex-trem** [symfony/demo#1212]
Right after cloning I got these errors

Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:8000/build/898.css' with computed SHA-256 integrity 'E5zkZMFh4ciL8QJJZZR452j+wYp+8ulpPiWokrNMbLk='. The resource has been blocked.
fr:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:8000/build/app.css' with computed SHA-256 integrity 'Wd+qhjxcJUD8sZaBwpfPKS5+S6PnRj1NRKTeKj1uCY0='. The resource has been blocked.
fr:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:8000/build/755.js' with computed SHA-256 integrity 'Jd1MaErPlkx9j1xA2ExLBaypwokbb//GEn/bB1WqpDM='. The resource has been blocked.

**Comment by NCapiaumont** [comment]
up

**Comment by NCapiaumont** [comment]
Run : 
`$ composer install`
`$ npm install`
`$ npm run build`

**Comment by seb-jean** [comment]
@Alex-trem , Is it resolved?

**Comment by Preakaelis** [comment]
For me, I had the same problem and it's solve, thank you
