### ISSUE TITLE
No vendor folder

### ISSUE THREAD

**Issue by threed-factory-store** [symfony/demo#1228]
public/index.php has this line:
`require_once dirname(__DIR__).'/vendor/autoload_runtime.php';`

dirname('public') takes us to demo-main which has no vendor folder.

What aren't you telling us?

**Comment by endelwar** [comment]
You must run `composer install` to download vendors and autogenerate `/vendor/autoload_runtime.php`

**Comment by bocharsky-bw** [comment]
Hey @threed-factory-store,

Please, follow the installation guide in the README to install it in a simple way: https://github.com/symfony/demo#installation

If you install this project in another (more advanced) way - we already suppose you know the basics of Composer

**Comment by javiereguiluz** [comment]
Victor is right. We provide two different commands to install the project (via Symfony CLI and via Composer). Both commands create the `vendor/` directory and download everything that is needed. If users prefer other installation methods, we can't provide the instructions for it. Thanks for understanding!
