### ISSUE TITLE
Prefer PHP configs over YAML to comply with Symfony core approach?

### ISSUE THREAD

**Issue by TomasVotruba** [symfony/demo#1264]
Hi,

I'm currently writing feedback on one Symfony project and one of points is `/config` directory. I'm writing few evidence provided by Symfony itself, why it's practise to follow:

* [Symfony GitHub issue] Symfony moved own configs to PHP in June 2020  https://github.com/symfony/symfony/issues/37186
* [Symfony Blog] Symfony 5.3 builder classes - https://symfony.com/blog/new-in-symfony-5-3-config-builder-classes
* [Symfony Twitter] Symfony twitter mentions the [symplify/config-transformer](https://github.com/symplify/config-transformer) to use to move XML/YAML to PHP https://mobile.twitter.com/symfony_en/status/1284538366147678208

This is quite strong evidence and its good :+1: 

On the other hand, this is rather partial know-how, that only few people follow. The most community and projects use the defaults. One of defaults is this project, and at the moment, the `/config` directory is [mix of PHP and mostly YAML](https://github.com/symfony/demo/tree/main/config). So people use YAML everywhere :upside_down_face: 

This is confusing, as some official Symfony blog posts, tweets and issues promotes PHP configs, but default project is still using YAML.

Saying that, I think it might bring better DX to use PHP here too. What do you think? 

<br>

(I've done the migration on dozens of Symfony projects now, so I can send PR.)

**Comment by stof** [comment]
The symfony/demo project is applying the Symfony flex best practices by design of the project. And for now, this is still about using YAML (the internal config files of FrameworkBundle are totally unrelated to this `config/` folder, and they were not even in YAML before either).

And this repo is not the place to discuss a change of the official recommendation (that should be discussed in the symfony/symfony repo)

**Comment by TomasVotruba** [comment]
Thanks for comment. What does "Symfony flex best practices by design of the project"? It's first time I hear about it.

**Comment by stof** [comment]
> What does "Symfony flex best practices by design of the project"? It's first time I hear about it.

I added a comma in the sentence, which should make it easier to understand.

> I talk mainly about DX of mixed approach to use configs, not about what this project uses.

and that's precisely why this repo is the wrong place to talk about it. This demo project does not decide by itself which format it uses. It applies whatever the current Symfony standard is, and right now, it is YAML for the DI config files.

Note that `config/bundles.php` and `config/preload.php` are a totally different kind of config files, configuring other parts of the project (or of PHP-FPM in case of preload)

**Comment by javiereguiluz** [comment]
Let's close this old issue for the reasons explained by Christophe: we must follow what Symfony recommends to do. So, we must keep using YAML for config (although Symfony turned its internal config from XML to PHP). In any case, thanks Tomáš for your proposal!
