### ISSUE TITLE
[V1.8.0] Unable to connect with symfony/security-bundle:5.4.1

### ISSUE THREAD

**Issue by cavasinf** [symfony/demo#1283]
I don't know if it's linked or not.

But I've started 15 days ago a new project with `[V1.8.0] Symfony/demo 5.4`.
I've update my composer packages today, which include `symfony/* 5.4.1` (released 4 days ago from today)

After that update, I can no longer connect any users into my APP.

What is wrong ?

**Comment by stof** [comment]
The demo issue tracker is not a support channel for your own projects.

and this is probably related to https://github.com/symfony/symfony/issues/44546

**Comment by cavasinf** [comment]
I mean .. it's only a `symfony new --demo my_project` and not MY project.

Not my fault if a demo project is not working...

**Comment by javiereguiluz** [comment]
Let's close this issue. Hopefully this was fixed a long time ago. Thanks.
