### ISSUE TITLE
EnumType ?

### ISSUE THREAD

**Issue by seb-jean** [symfony/demo#1313]
Hey :),
Would it be cool to propose the `EnumType` type in `PostType`?
What do you think ?

**Comment by bocharsky-bw** [comment]
Do you have a good use case for this? Please, feel free to share

**Comment by seb-jean** [comment]
A post status like WordPress ?
https://wordpress.org/support/article/post-status/#default-statuses

**Comment by javiereguiluz** [comment]
I'd prefer if we didn't modify code just to use Enums. Given that it's a PHP feature, not a Symfony feature, we are not required to use it if we don't find a good use case for it.

I've looked into code and the only "group of constants" (a good indicator to introduce Enums) is this one: https://github.com/symfony/demo/blob/f1ee7c6b8a70f8fed2ca032052a7760d58299cef/src/Security/PostVoter.php#L31-L33

What do you think? Thanks!

**Comment by seb-jean** [comment]
The idea was to show that `EnumType` exists.

**Comment by seb-jean** [comment]
I close the issue?

**Comment by stof** [comment]
Btw, if the goal is to showcase the doctrine/orm feature supporting enums (as suggested by the ticket title, as `enumType` in the name of the configuration setting for that feature), such use case needs to be found in the data model.

**Comment by seb-jean** [comment]
Yes, that's it, that's the goal.
