### ISSUE TITLE
Use logout_path() helper + add CSRF protection to logout

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1314]
after these changes Use logout_path() helper + add CSRF protection to logout

change password is not working , Invalid CSRF token.

in UserController 
return $this->redirectToRoute('security_logout');

**Comment by bocharsky-bw** [comment]
I suppose we need to leverage `LogoutUrlGenerator::getLogoutPath()` in that spot too, which should fix the problem. Could you try this and probably create a PR?

**Comment by alexis78-sym** [comment]
@lxregistry Do you still have the problem?
