### ISSUE TITLE
Change duration of login expiry

### ISSUE THREAD

**Issue by marksmanpilotcurler** [symfony/demo#1326]
All --
    The symfony demo (PHP 8, SF 6), appears to use the symfony security services to implement a login/logout function.  The default time for a login to expire, without activity, appears to be one hour (3600 seconds).   One can search the code and see 3600 hardwired in a couple of places.

    **Is there any recommended way to change the 3600 second value default login expiry time value to another number?**
                 Best....Doug

**Comment by javiereguiluz** [comment]
Sorry for the super late reply. In case someone ends up here, check the `cookie_lifetime` config option: https://symfony.com/doc/current/reference/configuration/framework.html#cookie-lifetime
