### ISSUE TITLE
Suggestion: post slug should not been overidden

### ISSUE THREAD

**Issue by ecourtial** [symfony/demo#1333]
:wave: 

In this line:

https://github.com/symfony/demo/blob/7ca89270d3b9255e348bdb0c360ebe9b4d57e1a2/src/Form/PostType.php#L82

We see that the slug is always created/updated if the title is not empty.
Issue: when editing a post which has already been published and indexed by search engines, it could trigger a side effect if you change the title.

I suggest:

>if (null === $post->getSlug()) {
>$post->setSlug($this->slugger->slug($post->getTitle())->lower());
>}`

**Comment by bocharsky-bw** [comment]
Makes sense to me 👍

**Comment by ecourtial** [comment]
@javiereguiluz 
Allright I will create the PR soon.

**Comment by javiereguiluz** [comment]
Fixed in #1338. Thanks!
