### ISSUE TITLE
Upgrade yarn packages to latest

### ISSUE THREAD

**Issue by tacman** [symfony/demo#1342]
Since this is the demo program that shows best practices, is there any reason not to update to the latest packages?  In particular, Webpack and stimulus.

```
@symfony/stimulus-bridge      2.1.0   -> 3.2.1                                                     
@symfony/webpack-encore       1.4.0 ->  2.1.0                                 
stimulus                      2.0.0  ->  3.0.1  
 ``` 

I'm happy to do a PR, but wanted to see if there was any particular reason to keep these older versions in the branch that works with 6.1.

**Comment by javiereguiluz** [comment]
There's no reason to keep the old versions, so please submit a PR to update this. Thanks!

**Comment by 94noni** [comment]
@javiereguiluz great news, yes and as explain I got some conflict/problem trying to recompile new assets before versioning them :s 
anyways, nice that this project is up to date now :)
