### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by LeikoDmitry** [symfony/demo#1348]
Then I run the command for installation project:

`composer create-project symfony/symfony-demo my_project`

I am getting the error:
`Could not find package symfony/symfony-demo with stability stable in a version installable using your PHP version, PHP extensions and Composer version.`

PHP 8.1.8.
Composer 2.3.10

**Comment by javiereguiluz** [comment]
I've just run the command and it worked for me as expected:

<img width="494" alt="" src="https://user-images.githubusercontent.com/73419/179926187-8fe66956-b5b0-403b-a43f-f529b47afa44.png">

Let's see if we can find why it failed for you 🤔

**Comment by LeikoDmitry** [comment]
Hmm...
![Screenshot from 2022-07-20 10-53-36](https://user-images.githubusercontent.com/9258971/179927828-e1fae2a2-1f41-4550-9ad2-8977ccec9b0b.png)

Also I used the ubuntu 21.10

**Comment by LeikoDmitry** [comment]
> Do you have a global composer config file disabling the packagist.org repository ?

No I don't have any config files for composer :)

**Comment by nasgir** [comment]
Same issue.
Composer 2.3.8
PHP 8.1.8
Ubuntu 21.10

**Comment by 7ochem** [comment]
It works for me on Ubuntu 18.04.6, PHP 8.1.8, Composer 2.3.7.

I have loads of PHP extensions installed. If I remove php8.1-sqlite, then it also fails for me:

```
$ composer create-project symfony/symfony-demo my_project
Creating a "symfony/symfony-demo" project at "./my_project"

In CreateProjectCommand.php line 435:

  Could not find package symfony/symfony-demo with stability stable in a version installable using your PHP version, PHP extensions and Composer version.
```

**Comment by stof** [comment]
@7ochem the upcoming composer 2.4 version will provide a better error message when there is no version compatible with your platform, by giving more details.

**Comment by 7ochem** [comment]
@stof that's exactly what I was going to add to my comment: Seems like a Composer issue that the message doesn't clearly state what is missing. Something like the output of `composer why-not symfony/symfony-demo`, except that you can't run `composer why-not` when you don't have composer initialised in your current working dir.

**Comment by UtechtDustin** [comment]
I have the same problem, i'm using Ubuntu 20.04 with PHP 8.1.8
I can confirm that the issue is fixed after installing `php8.1-sqlite3` as @nasgir suggest.

**Comment by stof** [comment]
@7ochem indeed. The extra info is displayed in `composer require` but not in `composer create-project`. I opened https://github.com/composer/composer/issues/10959 about it.

**Comment by LeikoDmitry** [comment]
When I add the sqlite php extension:
`sudo apt install php8.0-sqlite3`
The issue is fixed :)
For `composer create-project` need more details

**Comment by LeikoDmitry** [comment]
I've removed the php8.1-sqlite3 also I upgraded the `composer` version 2.4 and try to itnstall the symfony demo application, however, I saw the error:
![Screenshot from 2022-07-21 18-45-55](https://user-images.githubusercontent.com/9258971/180257172-61ba31a8-86d3-443f-bf32-c12f8a11e015.png)

Although the issue is for php sqlite extension :(

**Comment by stof** [comment]
Well, here, it shows that the latest version is not compatible with your platform due to the PHP version itself.

It indeed does not show warnings for *all* candidate versions

**Comment by LeikoDmitry** [comment]
On my laptop was php version 8.0. I upgraded version and the `compmoser` showed more detail:
![Screenshot from 2022-07-21 22-23-25](https://user-images.githubusercontent.com/9258971/180299273-fa613cb5-70ff-4e94-8672-8014e21ff5b7.png)
Composer should be 2.4 version

**Comment by gvlasov** [comment]
On Manjaro. Had to manually enable `pdo-sqlite` in php.ini for this to work:

```
> symfony new ./symfony_demo --demo
* Creating a new Symfony Demo project with Composer
  (running /home/chriego/.local/bin/composer create-project symfony/symfony-demo /home/chriego/Projects/personal/symfony_demo  --no-interaction)

Creating a "symfony/symfony-demo" project at "./symfony_demo"
Cannot use symfony/symfony-demo's latest version v2.4.0 as it requires ext-pdo_sqlite * which is missing from your platform.
```

Notice the last line

```
vim /etc/php/php.ini
```

Find line `;extension=pdo_sqlite` and remove the `;`
