### ISSUE TITLE
PHPStan - Symfony + Doctrine

### ISSUE THREAD

**Issue by seb-jean** [symfony/demo#1379]
It would be interesting to add [Symfony extension for PHPStan](https://github.com/phpstan/phpstan-symfony) and [Doctrine extensions for PHPStan](https://github.com/phpstan/phpstan-doctrine).

**Comment by javiereguiluz** [comment]
I agree! If anyone is interested, please submit a PR because we'll merge it for sure and help you if you need it. Thanks!
