### ISSUE TITLE
Enable foreign keys in SQLite

### ISSUE THREAD

**Issue by TomaszGasior** [symfony/demo#1393]
I've just saw this: 

https://github.com/symfony/demo/blob/b0526f449cd8348b0ba18d26492c7db9429b70f4/src/Controller/Admin/BlogController.php#L171-L174

In my open source app I reconfigure SQLite to enable foreign keys using Doctrine functionality. Maybe symfony/demo app could do something similar?

https://github.com/TomaszGasior/RadioLista-v3/blob/8cbd969424bf043ae372b4215f0395d61a970897/src/Doctrine/Middleware/SqliteForeignKeyMiddleware.php#L11-L29

That's based on https://github.com/doctrine/dbal/blob/3.5.x/src/Driver/AbstractSQLiteDriver/Middleware/EnableForeignKeys.php but doesn't crash the app if another DBMS is used.

**Comment by javiereguiluz** [comment]
Tomasz, the solution that you proposed is great ... but given that this is a demo application just to showcase Symfony, each and learn Symfony and benchmark Symfony, I think it's better to not complicate the application to implement this feature.

Using SQLite is convenient for the idea of this project (create a 100% stand-alone app that doesn't require to install, run or configure anything). However, most real apps will use PostgreSQL, MySQL, etc. so we shouldn't try to fix SQLite shortcomings. Thanks for your understanding.

**Comment by TomaszGasior** [comment]
> However, most real apps will use PostgreSQL, MySQL,

And that's the exact reason why it may make sense to enable foreign keys in SQLite: because all of real-world apps will have foreign keys enabled by default in MySQL or PostgreSQL.

**Comment by TomaszGasior** [comment]
It's already included in Doctrine DBAL but the way how it's currently implemented makes it impossible to easily swap database driver. This is explained here in the issue description ↑↑↑

**Comment by TomaszGasior** [comment]
Yes, and there is nothing wrong with that. It's already included in Doctrine DBAL which is installed when you have Doctrine bundle installed.

**Comment by TomaszGasior** [comment]
If you don't want to have that class in your app, you can just add `Doctrine\DBAL\Driver\AbstractSQLiteDriver\Middleware\EnableForeignKeys` to your services.yaml and tag with proper tag `doctrine.middleware`.

As I described, if you do that in your app, the app will not work with driver other than SQLite one because implementation built into Doctrine DBAL is not conditional: that's the reason why it may make sense to have this little file in your app, to have better control.

**Comment by derrabus** [comment]
I don't think you get my point. Nevermind.
