### ISSUE TITLE
No route found Error

### ISSUE THREAD

**Issue by team-mate** [symfony/demo#1419]
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost:8100/en/login/"" at C:\xampp\htdocs\bauer\bauer-iot-portal-bt\vendor\symfony\http-kernel\EventListener\RouterListener.php line 127
![Capture](https://user-images.githubusercontent.com/102652138/236375904-5f111c68-f62c-4fe9-91cb-2340cb5935bb.PNG)

**Comment by javiereguiluz** [comment]
Let's close because of the lack of feedback. Hopefully was a temporary misconfiguration that was already solved.
