### ISSUE TITLE
Translation editor for XLIFF

### ISSUE THREAD

**Issue by Mecanik** [symfony/demo#1436]
Hey, what tool did you use to edit these files easily? Poeditor seems to struggle with it.

Thanks

**Comment by javiereguiluz** [comment]
Personally I don't use any special editor for these XLIFF files. I use SublimeText and/or PhpStorm to edit those.

**Comment by Mecanik** [comment]
Yeah that's a pain when you have many strings to translate... I might make a small script and share it.

**Comment by javiereguiluz** [comment]
We didn't receive more feedback about this from the community, so let's close it. Thanks.
