### ISSUE TITLE
Symfony 7 Demo and Migration Questions

### ISSUE THREAD

**Issue by tacman** [symfony/demo#1447]
I have a version of this demo working with Symfony 7 for everything except doctrine/doctrine-fixtures-bundle

```bash
git clone git@github.com:tacman/symfony-demo.git --branch=symfony7 symfony7-demo && cd symfony7-demo
composer install && yarn install && yarn dev
symfony server:start -d
symfony open:local
```

The PHP part works fine, but there are issues with stimulus.  I imagine others who are migrating to Symfony 7 may run into the same issues, so maybe this issue can be the beginning of a migration guide.

In particular, when using both webpack and AssetMapper, should there be TWO app.js files, once that's the entrypoint for the importmap and the other that's for webpack?  If I load javascript dependencies via Assetmapper / importmap, will they be available in my webpack-handled javascript?

            {{ encore_entry_script_tags('app') }}

And in particular, how should the stimulus bootstrap file (which of course needs to change from the bridge to the stimulus-bundle).    Currently it fails:

```
 ERROR  Failed to compile with 1 errors                                                                                                                       8:16:37 AM

Module build failed: Module not found:
"./assets/bootstrap.js" contains a reference to the file "@symfony/stimulus-bundle".
This file can not be found, please check it for typos or update it if the file got moved.
```

Of course, I'd eventually love to get rid of the whole yarn install && yarn dev step, but in practice I'm sure I'll need it in my own projects for a while, and so understanding how to use them both will be important.

**Comment by javiereguiluz** [comment]
_I'm not answering to your question, but I'm adding a quick comment here: for Symfony Demo, first we'll tag and release a version of the project using Symfony 6.4 (see #1431) and soon after that, we'll update the project to 7.0, tag it and release it._

_Also, we don't maintain multiple versions of this project. We only use the current stable version. That's why the version using Symfony 7.0 will be the only maintained version. Thanks!_
