### ISSUE TITLE
Doctrine\DBAL\Connection::setNestTransactionsWithSavepoints is deprecated and will be removed in 5.0

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1503]
User Deprecated: Doctrine\DBAL\Connection::setNestTransactionsWithSavepoints is deprecated and will be removed in 5.0 (Connection.php:948 called by App_KernelDevDebugContainer.php:752, https://github.com/doctrine/dbal/pull/5383, package doctrine/dbal)

after composer update

![Screenshot 2024-02-28 203742](https://github.com/symfony/demo/assets/32699348/3b000688-a3d5-4626-aa8a-a1c229a8c74d)

**Comment by dmaicher** [comment]
You are having this issue with Symfony Demo? Or your own project?

Here we are not configuring `use_savepoints` anymore since https://github.com/symfony/demo/pull/1494.

So I don't understand your issue.

**Comment by bocharsky-bw** [comment]
I suppose that may be an indirect deprecation
