### ISSUE TITLE
deprecation log message

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1507]
Since doctrine/doctrine-bundle 2.12: The default value of "doctrine.orm.controller_resolver.auto_mapping" will be changed from `true` to `false`. Explicitly configure `true` to keep existing behaviour

After update, I receive this log message.
In doctrine.yaml this auto_mapping exist, not sue what is wrong.

maybe it should be in this format:
`
doctrine:
   orm:
        controller_resolver:
            auto_mapping: true
`

**Comment by xabbuh** [comment]
Can you check if the deprecation message vanishes, when you update your config like in #1508?
