### ISSUE TITLE
User Deprecated: Since twig/twig 3.10

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1518]
after update

Upgrading twig/twig (v3.10.1 => v3.10.2): Extracting archive

User Deprecated: Since twig/twig 3.10: The "Twig\Extension\EscaperExtension::addSafeClass()" method is deprecated, use the "Twig\Runtime\EscaperRuntime::addSafeClass()" method instead.

**Comment by derrabus** [comment]
Duplicate of symfony/ux#1844.

**Comment by lxregistry** [comment]
this deprecation notice still persist
 Installing twig/twig (v3.10.3): Extracting archive

User Deprecated: Since twig/twig 3.10: The "Twig\Extension\EscaperExtension::addSafeClass()" method is deprecated, use the "Twig\Runtime\EscaperRuntime::addSafeClass()" method instead.

**Comment by derrabus** [comment]
Please use https://github.com/symfony/symfony/discussions for support questions.
