### ISSUE TITLE
Access Denied for route on /admin/post

### ISSUE THREAD

**Issue by mehdichaouch** [symfony/demo#1527]
Hello,

On a clean install I get for route `/admin/post`:
![image](https://github.com/user-attachments/assets/783f3a68-d05c-40d2-aba2-d74bb1a2e07a)

Any idea?

Merci

**Comment by derrabus** [comment]
Your user does not have the necessary roles to access that page.

**Comment by mehdichaouch** [comment]
@derrabus I just play the migration. The issue is in it?

**Comment by xabbuh** [comment]
The demo application has two users (`john_user` and `jane_admin`). You need to sign in as `jane_admin` (you are currently logged in as `john_user`) to be able to access the admin area.

**Comment by mehdichaouch** [comment]
> The demo application has two users (`john_user` and `jane_admin`). You need to sign in as `jane_admin` (you are currently logged in as `john_user`) to be able to access the admin area.

@xabbuh ok thank your answer.

**Comment by CraigAT** [comment]
Glad I found this, as I thought I had an issue with the demo app.  Thanks @xabbuh 
I would have expected the app to have dealt with the issue more gracefully, perhaps by warning that john_user didn't have access.
