### ISSUE TITLE
Update Entities to use Doctrine 2.6 types

### ISSUE THREAD

**Issue by HeahDude** [symfony/demo#620]
Thanks to https://github.com/symfony/symfony/pull/22689 `Comment` and `Post` entities should now use the new `date time_immutable` type for their `$publishedAt` property, so getters/setters should accept `DateTimeInterface`.

If you agree, this should be an easy pick.

**Comment by javiereguiluz** [comment]
It looks like a good idea! But let's not submit any pull request until #617 is merged. Thanks!

**Comment by voronkovich** [comment]
Also we should replace the `json_array` type by `json` because the `json_array` is deprecated since Doctrine 2.6.

**Comment by javiereguiluz** [comment]
This proposal is now unlocked and ready for someone who wants to contribute to this project with this easy pick. Thanks!

**Comment by gabel** [comment]
I guess `datetime_immutable` can not be applied as the `\App\Controller\Admin\BlogController::newAction` uses handle($request) which transforms the input into a `\DateTime` object and that would break the ORM mapping. Looks like this is related to https://github.com/symfony/symfony/pull/19889.

If you need more details I can provide a PR with example implementation.

**Comment by gabel** [comment]
Talk is cheep.. PR is here https://github.com/symfony/symfony-demo/pull/659 but test failing due to the mentioned issue.

**Comment by javiereguiluz** [comment]
Let's close this as "fixed". The JSON types are now used and the immutable date can't be used because of Symfony Forms. The related issue (https://github.com/symfony/symfony/issues/9508) has been opened for more than 4 years, so this is more difficult to implement than it looks. Thanks!
