### ISSUE TITLE
[RFC] How should we update this application for Symfony 3.4 and 4.0?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#671]
The latest stable version of this application uses Symfony 3.3 + Flex. I'd like to start updating it for Symfony 3.4 and/or 4.0 as soon as possible to help spotting bugs and problems.

Considering that 3.4 and 4.0 are released on the same day, which version should we update to? I'd say it's better to upgrade to 4.0 directly, because it may contain breaks and bigger changes than 3.4. Would you agree? Can you imagine a better upgrade path to help Symfony?

*Note: we won't create two branches (one for 3.4 and "master" for 4.0) because of the management overhead. We'll keep using just 1 branch. Thanks!*

**Comment by yceruto** [comment]
:+1: for 4.0

**Comment by stof** [comment]
Well, you need to upgrade to 3.4 first anyway, to get the new deprecation warnings. Upgrading from 3.3 to 4.0 directly is not supported by the continuous upgrade path (you need to go to the last minor release of a version before bumping the major version for the process to work).

However, I agree that the final target of the migration should be 4.0. Until now, the policy for this demo was to use the latest release of Symfony, not the LTS version.

**Comment by stof** [comment]
Note that once you are on 3.4 and you don't get any deprecation warning, migrating to 4.0 should be a no-brainer.

Also, be careful with the migration to 3.4 when using Flex. As you rely on transitive dependencies (you don't depend explicitly on the DI component for instance) and Symfony 3.4 allows to use 4.0 versions for all of its inter-component dependencies, you should use the `symfony/lts` package to force all packages to stay at version 3 until you are ready to upgrade.

**Comment by yceruto** [comment]
WIP https://github.com/yceruto/symfony-demo/tree/upgrade_to_34 ;)

**Comment by javiereguiluz** [comment]
OK. Let's close this and let's upgrade to 3.4 and when all deprecations are gone, upgrade immediately to 4.0. We won't release a stable release for 3.4, just for 4.0. Thanks!
