### ISSUE TITLE
Remove Makefile

### ISSUE THREAD

**Issue by garak** [symfony/demo#680]
See https://twitter.com/fabpot/status/920065125238824961

**Comment by yceruto** [comment]
See https://github.com/symfony/demo/pull/673/commits/f9ed1d6322f9404c1c04ed31a681918deb9863a9 thanks.

**Comment by javiereguiluz** [comment]
@garak thanks! You are right ... but we're making that change as part of the global effort to upgrade the application to 3.4 and 4.0 in #673, so I'm closing this as "duplicate".
