### ISSUE TITLE
ORDER BY clause is not in SELECT list

### ISSUE THREAD

**Issue by KirbyFox** [symfony/demo#683]
Converted this to use MySQL and it throws the following exception:

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.publishedAt_5' which is not in SELECT list; this is incompatible with DISTINCT").

**Comment by javiereguiluz** [comment]
We received the exact same issue report in https://github.com/javiereguiluz/EasyAdminBundle/issues/1871. Is this really a misuse on our side ... or a bug in the pagination bundle?

**Comment by stof** [comment]
This should be reported to the Doctrine ORM project, as it is the one implementing the ORM pagination.
And please include the DQL query being paginated in the issue report, as well as the mysql configuration regarding strict mode and related settings (MySQL changes its behavior a lot based on these options regarding what is valid in SQL).

**Comment by javiereguiluz** [comment]
Let's close this old issue as suggested by Christophe. Thanks.

**Comment by jywarren** [comment]
Linking together some threads here - i believe it has to do with mysql version (we were able to bypass by using 5.7) and/or strict mode: https://github.com/publiclab/plots2/pull/8145

Thanks!
