### ISSUE TITLE
failed to deploy on heroku

### ISSUE THREAD

**Issue by cybernet** [symfony/demo#686]
`ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
Database schema created successfully!

[37;41m                                                                          [39;49m
[37;41m  [Symfony\Component\DependencyInjection\Exception\EnvNotFoundException]  [39;49m
[37;41m  Environment variable not found: "MAILER_URL".                           [39;49m
[37;41m                                                                          [39;49m

[32mdoctrine:schema:create [--dump-sql] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] [39m[32m<command>[39m`

**Comment by javiereguiluz** [comment]
@cybernet thanks for reporting it! Could you please try if the #687 change solves the issue? Thanks!

**Comment by cybernet** [comment]
no :(

[37;41m                                                                          [39;49m
[37;41m  [Symfony\Component\DependencyInjection\Exception\EnvNotFoundException]  [39;49m
[37;41m  Environment variable not found: "DATABASE_URL".                         [39;49m
[37;41m                                                                          [39;49m

**Comment by javiereguiluz** [comment]
@cybernet we finally solved the original `MAILER_URL` bug (see #687) but regarding the other issue about `DATABASE_URL`, according to [this comment](https://github.com/symfony/demo/pull/687#discussion_r150211584) you need to install or configure or enable some addon on Heroku. Cheers!
