### ISSUE TITLE
translations not working

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#704]
hello,
installed today latest version with git clone

An exception has been thrown during the rendering of a template ("Invalid resource provided: "1.2"; Errors: [WARNING 1549] failed to load external entity "file:////var/www/vhosts/test.domain/symfony/vendor/symfony/translation/Loader/schema/dic/xliff-core/xml.xsd" (in n/a - line 0, column 0)

**Comment by javiereguiluz** [comment]
I can't reproduce this error. During the last days we changed translations from translations/ to config/translations/ and then back to translations/. The definitive dir is `translations/`. Can you check if the files are in that directory?

**Comment by bogdandovgopol** [comment]
Working for me just fine.

**Comment by bogdandovgopol** [comment]
@javiereguiluz Working for me just fine.

**Comment by piotrgradzinski** [comment]
@javiereguiluz - works OK for me too. Can't reproduce.

**Comment by javiereguiluz** [comment]
OK, thanks for your comments. I'm closing this issue then until we have more information about how to reproduce it. Thanks!
