### ISSUE TITLE
No .htaccess

### ISSUE THREAD

**Issue by dzuelke** [symfony/demo#711]
There is currently no `.htaccess` file in place with rewrites that remove `index.php`, so out of the box, the demo doesn't work beyond the first page. Is that intentional?

**Comment by jkufner** [comment]
Commiting .htaccess is a bad practice, because it complicates deploy. However, it would be nice to have example config files for the most used web servers in the documentation.

**Comment by piotrgradzinski** [comment]
@dzuelke - as per @jkufner comment this is considered as a bad practise. 

Check [Configuring a Web Server](http://symfony.com/doc/current/setup/web_server_configuration.html) documentation section for an explanation and information on how you should configure your web server. 

Nevertheless you can use `apache-pack` recipe for adding `.htaccess` to you `public` folder by executing 

`composer require apache-pack`.

Hope this helps and answers you concern.

**Comment by bocharsky-bw** [comment]
Actually a good point. As far as we have a "Deploy to Heroku" button in README, we should have a proper `.htaccess` for it as well to make it working out of the box

**Comment by dzuelke** [comment]
Yeah I'm mostly interested in having it work out of the box on as many setups as possible, as it's a demo app. I could easily do a PR with a Heroku specific config or something, but would rather not clutter the repo with a vendor specific thing (the demo right now is not working on Heroku, for other reasons as well, such as SensioDistributionBundle being gone which used to write the `Procfile`).

**Comment by javiereguiluz** [comment]
It's true that we don't care about `.htaccess` in this demo app because we recommend to use the Symfony server (`bin/console server:start` command) to browse the app.

However, I agree that this should work out-of-the-box on Heroku (unless that requires us to change our code). We already have an `app.json` with Heroku config and stuff (https://github.com/symfony/demo/blob/master/app.json). Could we make more changes in that file to fix this issue? Thanks!

**Comment by dzuelke** [comment]
For that we'd need a separate `Procfile`, but I think I'll add support for automatic detection of Symfony to Heroku's PHP support. For that I need a definitive answer to https://github.com/symfony/symfony-docs/issues/8766 though.

**Comment by javiereguiluz** [comment]
Let's close this in favor of the automatic detection feature on Heroku proposed by David ... and we'll reopen this if that's not possible to implement for any reason.
