### ISSUE TITLE
Attempt to concatenate local 'package_version'

### ISSUE THREAD

**Issue by 5-digits** [symfony/demo#714]
when start runing the server 
php bin/console server:start
I found out that Error :  
...t\programs\cmder/vendor/clink-completions/npm_prompt.lua:11: attempt to concatenate local 'package_version' (a nil value)

**Comment by javiereguiluz** [comment]
This error looks unrelated to the Symfony Demo application. Maybe it's related to this: https://github.com/cmderdev/cmder/issues/700  If you have more information or a way to reproduce, please reopen the issue. Thanks!
