### ISSUE TITLE
composer create-project does not use Symfony 4

### ISSUE THREAD

**Issue by KirbyFox** [symfony/demo#715]
I ran composer create-project symfony/symfony-demo but it creates a Symfony 3.3 project.

**Comment by javiereguiluz** [comment]
When you run `composer create symfony/symfony-demo`, you get the 1.1.1 version of the project (which still uses Symfony 3.3):

![1](https://user-images.githubusercontent.com/73419/33517203-00951a6e-d780-11e7-89f8-9fc6f59c4209.png)

But the 1.2.0 version should be installed, which was released on GitHub:

![2](https://user-images.githubusercontent.com/73419/33517206-0a51a2ca-d780-11e7-8c5a-4320f45f3c0d.png)

And exists as a Git tag:

![3](https://user-images.githubusercontent.com/73419/33517207-0ff607fc-d780-11e7-8b7c-17c8acf9af3d.png)

But it's not available on Packagist, which is what Composer uses:

![4](https://user-images.githubusercontent.com/73419/33517210-181aa1a4-d780-11e7-81cc-93738bdab024.png)

Where is the error? I have no idea 😅  ... so please, can anybody help us here? Thanks!

**Comment by KirbyFox** [comment]
I had to resort to downloading the files and then running composer update, which worked fine.

**Comment by phpeek** [comment]
@javiereguiluz Can You check an update log as mentioned here - https://medium.com/packagist/tagged-a-new-release-for-composer-and-it-wont-show-up-on-packagist-org-or-on-private-packagist-efaf21c212ff

Maybe it would say something regarding this issue.

**Comment by javiereguiluz** [comment]
I've released 1.2.1 version ... but Packagist still ignores it: https://packagist.org/packages/symfony/symfony-demo

@phpeek thanks for that article. I've read it and I don't see any error ("composer validate", etc.) So, what's going on here?

**Comment by phpeek** [comment]
Hm... Very strange.

@javiereguiluz Just be 100% sure I would update GitHub repo URL on packagist.org since it's still pointing to https://github.com/symfony/symfony-demo.

**Comment by javiereguiluz** [comment]
Fabien has fixed the issue. `composer create symfony/symfony-demo` now installs Symfony 4.0.1 🎉
