### ISSUE TITLE
FileLoaderLoadException

### ISSUE THREAD

**Issue by laajilyanas** [symfony/demo#732]
The file "D:\sfProjects\developpement\sf3\app/config\services.yml" does not contain valid YAML in D:\sfProjects\developpement\sf3\app/config\services.yml (which is being imported from "D:\sfProjects\developpement\sf3\app/config\config.yml").

#symfony3

**Comment by javiereguiluz** [comment]
This repository is not the best place to report this issues about using Symfony. Please use any of the available support channels: https://symfony.com/support  Thanks!
