### ISSUE TITLE
Support accented chars in search

### ISSUE THREAD

**Issue by ZHB** [symfony/demo#734]
Hello,

Currently query search sanitization replace all non alphanumeric chars :

```preg_replace('/[^[:alnum:] ]/', '', ...);```

and accented chars like éèà... are removed too, making posts not findable for accented articles. Maybe supporting accented chars would be nice for all non english people using this demo app as a base ?

**Comment by javiereguiluz** [comment]
This definitely looks like a bug because we've translated this app into lots of languages with that kind of characters.
