### ISSUE TITLE
Why databases SQLite are in git?

### ISSUE THREAD

**Issue by ebuildy** [symfony/demo#744]
I am just wondering if it's a good practice to versionize such files?

**Comment by bocharsky-bw** [comment]
We keep it in Git to be able to launch this demo app in "one click", i.e. we already load fixtures there. Actually, a good practice probably is: does not use SQLite DB for production at all :)

**Comment by ebuildy** [comment]
well, SQLite is good for test I think, no need an extra server to run functional test, it's very cool!

I was wondering that because Codeception Symfony-demo is not saying anything about data fixtures, so now I know where is come from!

Thanks you,

**Comment by bocharsky-bw** [comment]
You know, I partially agree with you about using SQLite for testing, well, it's simple. But on the other side I'd prefer to test on the exact SQL server and even the exact version of this SQL server which I have in production. This way I'll be more confident in tests and queries I wrote.

You probably heard about some BC breaks in MySQL 5.7, so I don't want to see my tests passed on CI with SQLite, but have errors in production :)
