### ISSUE TITLE
base_path setting for application not in webroot / deployment sf 4 on iis

### ISSUE THREAD

**Issue by gitdiz** [symfony/demo#748]
Dear experts, 
I tried to run the symfony 4 symfony-demo on a intranet server on iis. I had some problems to get the assets (css and js) correctly loaded.

The demo lives in a subfolder, not in the webroot and there is no possibilty in creating virtual hosts and using a command line. I need to adjust the basepath for this demo.

After some  searching I found, that setting the `base_url `for` assets` in `/config/packages/framework.yaml  `to the local IP  of the server worked and loaded the asset correctly from `public/build` .
Setting the base_path (as physical path on the server) like

`base_path: 'C:/inetpub/wwwpub/sf/symfony-demo/public/' `
instead of  
`base_urls:  'http://192.168.1.203/sf/symfony-demo/public/'
`
does not work. In the sf4 documentation I found no working hint on how to set that path correctly.

I posted also on stackoverflow, https://stackoverflow.com/questions/48110731/symfony-4-deploy-on-iis-in-a-nested-directory
but got no sufficient solution yet.  Is it possibly a bug, or where am I wrong ?
Thanks a lot dirk

**Comment by javiereguiluz** [comment]
@gitdiz I'm sorry you are having problems making this work. I'd say that `/sf/symfony-demo/public/` should work in the `base_path` ... but on StackOverflow you said that it's not working for you.

In any case, in this repo we only discuss about Symfony Demo bugs and new features, so this kind of questions is better to ask them on StackOverflow, as you already did. I hope you find a good solution soon.

**Comment by gitdiz** [comment]
Thank you, this is a hint how it is intended to work!  The documentation is for me a bit misleading, since after hours still I could not identify , what this problem is really related to: base_path, web_root, document_root, rewrite_rules, assets, "extra.symfony-public-dir" in composer.json. I will ask this in the symfony forum!
