### ISSUE TITLE
Enhance Tag feature to work as a search for similar blog posts

### ISSUE THREAD

**Issue by CameraCornet** [symfony/demo#762]
Hello.  I think the Tag feature is great, but it seems incomplete as an example. When browsing the application, I would expect clicking a tag would show all other blog posts that have the same tag.

My request is enhancement to demonstrate best practices to implement this added ability.  Thank you.

**Comment by yceruto** [comment]
Agree and it should be fixed in https://github.com/symfony/demo/pull/765, thank you.
