### ISSUE TITLE
Q: APCu

### ISSUE THREAD

**Issue by kironet** [symfony/demo#775]
Hi,

Why you have symfony/polyfill-apcu installed, but you never use APCu in config/controller? 

Is it still recommended to use APC(u) with Symfony? 

Thanks

**Comment by stof** [comment]
@javiereguiluz does the currently version of the demo still relies on APCu as its caching layer or no ?

**Comment by stof** [comment]
hmm, in any case, the APCu polyfill is useless. It is here to emulate APCu on top of APC for older PHP versions, but the demo requires PHP 7.1+, so you either have APCu or nothing at all (and then the polyfill cannot help much)

**Comment by javiereguiluz** [comment]
We have this file: https://github.com/symfony/demo/blob/master/config/packages/prod/framework.yaml

```
#framework:
#    cache:
#        system: cache.adapter.apcu
```

**Comment by stof** [comment]
but anyway, we don't really need the APCu polyfill, due to our PHP version requirement
