### ISSUE TITLE
not working after composer update

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#783]
after composer update command I receive this error:

Cannot autowire service "App\Repository\PostRepository": argument "$registry" of method "__construct()" references interface "Doctrine\Common\Persistence\ManagerRegistry" but no such service exists. You should maybe alias this interface to the existing "doctrine" service.

could you explain what is wrong, please

**Comment by xabbuh** [comment]
FYI, this will be fixed by #782

**Comment by stof** [comment]
the 1.9.0 release of DoctrineBundle was buggy (one of the change was identified as a small BC break while it had a much bigger impact and the reason for the change did not justify such BC break out of major releases). The 1.9.1 release of the bundle fixes it.

So this issue should be closed.
