### ISSUE TITLE
how to design module  for application by symfony4.1? eg: web、api、app three module。

### ISSUE THREAD

**Issue by wukchao** [symfony/demo#813]
how to design module  for application by symfony4.1? eg: web、api、app three module。

**Comment by javiereguiluz** [comment]
@wukchao in modern Symfony apps we no longer divide the app into bundles or modules ("modules" was the word used in Symfony 1). This may be shocking, but once you get used to it, it's great. You achieve the same result, but faster and with a simpler structure and less files/dirs.

If you need a quick overview of how modern Symfony apps work, read [Symfony' Quick Tour](https://symfony.com/doc/current/quick_tour/the_big_picture.html). We can also help you with specific issues if you join [Symfony's Slack chat](https://symfony.com/slack-invite).
