### ISSUE TITLE
Where to get the vendor directory? Vendor/autoload.php no such file in bin/console

### ISSUE THREAD

**Issue by bellash13** [symfony/demo#815]
Downloaded this demo to test Symfony and their new features. It seems like `php bin/console server:run` is looking for the autoload.php function in the vendor directory, which is not present.
How to solve this? or where to get the vendor directory ?

**Comment by OlivierToussaint** [comment]
have you get composer ? (https://getcomposer.org)

If you have this, just run ```composer update``` in your demo rep

**Comment by javiereguiluz** [comment]
I'm closing this issue because of the lack of feedback. If there is some mistake when following the installation instructions step by step, please open a new issue with the error details. Thanks!
