### ISSUE TITLE
In templates/blog/post_show.html.twig where define these var

### ISSUE THREAD

**Issue by Anouchka25** [symfony/demo#825]
Hi
Please in templates/blog/post_show.html.twig where define these var : 

> action.sign_in
> post.to_publish_a_comment
> post.num_comments
> post.commented_on

Thanks

**Comment by OlivierToussaint** [comment]
Hi 

It's translation var : https://github.com/symfony/demo/blob/master/translations/validators.en.xlf

**Comment by Anouchka25** [comment]
Ok it work fine now, thanks
