### ISSUE TITLE
[Question] Should'nt the arrow icon be responsive?

### ISSUE THREAD

**Issue by sir-kain** [symfony/demo#829]
Is it relevant to change the orientation of the **arrow icon** that is before the text "Try either of the following users" on **the login page** for responsiveness reasons?

It's true that it has nothing to do with "learning symfony" but it's good aspect design of the application and to help the user.

If so, i am interested in doing a PR.

**Comment by javiereguiluz** [comment]
@sir-kain thanks for reporting! I agree this is something that must be fixed. I know you said you were willing to create a PR yourself ... but the change is minimal, so I did it myself: #840. But we'll be happy to get other contributions from you in the future. Thanks!
