### ISSUE TITLE
[BUG] cant install demo application

### ISSUE THREAD

**Issue by B4RD4k** [symfony/demo#844]
Hey i am using XAMPP, i installed composer in developer and choose the PHP of my XAMPP.
then wanted to create new symfony demo project using CLI composer.
I got this error message, please help

![image](https://user-images.githubusercontent.com/7777720/44000810-1c8c6850-9e2f-11e8-863d-57b618996aad.png)

**Comment by bobdenotter** [comment]
You can "fix" this by going into the `symfony-demo`, and running `composer update`. If you do, you'll get the latest version of flex.
