### ISSUE TITLE
Composer do not use latest version

### ISSUE THREAD

**Issue by roukmoute** [symfony/demo#848]
Hi,

I think there is a little problem to download the latest version with `create-project`.
So with the latest version of composer, it does not work.

https://asciinema.org/a/lVDqyeOibjIuszqcQkeqL0lLJ

Is it from composer or from this repository?

**Comment by roukmoute** [comment]
Packagist must be re-submitted?

**Comment by javiereguiluz** [comment]
I'm closing as "fixed" because the 1.2.5 version is now listed in Packagist. If the error persists, please reopen. Thanks!
