### ISSUE TITLE
Use with docker does not work

### ISSUE THREAD

**Issue by roukmoute** [symfony/demo#849]
I've tried to use `demo` with docker image but I don't know why, it doesn't work.
Do you have any idea?

https://asciinema.org/a/x4cIioVCMgGGiFKc9OuO7Suxu

And I've got this:

![image](https://user-images.githubusercontent.com/2140469/44089389-e28f22b6-9fc6-11e8-9347-4822f7a9ecf3.png)

I suppose that warning doesn't help but I don't know why:

`fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused)`

**Comment by javiereguiluz** [comment]
I'm not a Docker expert, so I can't help you. But, in #833 the community is proposing an official integration of this app with Docker, so please test that if you can and report issues in the related pull request. Thanks!
