### ISSUE TITLE
SomeController::loginAction() to SomeController::login(), etc.

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/demo#852]
Can I contribute by removing the "Action"-part of the controller's method names? E.g. in SecurityController:

loginAction() -> login()
logoutAction() -> logout()
...

It is now recommended to not include "Action" when naming controller methods: https://symfony.com/doc/current/best_practices/controllers.html

Please tell me if I can do this or if it is not a good idea.

**Comment by bocharsky-bw** [comment]
Since it's considered as best practices - let's do it 👍

**Comment by michaelKaefer** [comment]
Thanks for the reply, will do it as soon as possible!

**Comment by javiereguiluz** [comment]
@michaelKaefer friendly ping in case you forgot about this. We'd be glad to receive a pull request to improve this. Thanks!

**Comment by michaelKaefer** [comment]
This was already [done in 2017](https://github.com/symfony/demo/commit/549ed2c808172253afb301c93fcc084b30a9359e#diff-2cd1bd2ff3dc415cac2a8576e3eb6d98). I did composer create-project with PHP 7.0 on my CLI which installed an old version. Sorry!

**Comment by michaelKaefer** [comment]
@bocharsky-bw @javiereguiluz Next question: should it be mentioned in README.md that PHP smaller than 7.1 installed on CLI will install an old version without telling you? Or am I just dumb to not recognize it? :rofl:

**Comment by stof** [comment]
@michaelKaefer the readme already mentions current requirements of the demo: https://github.com/symfony/demo#requirements

**Comment by javiereguiluz** [comment]
OK, let's close this issue then. @michaelKaefer I'm sorry I didn't remember that we have already made this change. Cheers!

**Comment by michaelKaefer** [comment]
@stof Yes, but it does not say what happens if you have PHP CLI smaller than 7.1 (and maybe forgot to switch the CLI version). For me as a newcomer this was confusing. If not in README.md maybe a warning during the installation like: this is not the latest version, do you want to continue? I could try to implement it..
