### ISSUE TITLE
Fix the "tree builder without a root node" deprecation 

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#869]
These deprecations were introduced by the upgrade to Symfony 4.2 in #865.

```
53x: A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
    53x in AddUserCommandTest::testCreateUserNonInteractive from App\Tests\Command
```

**Comment by stof** [comment]
do you know which bundle this is ?

**Comment by javiereguiluz** [comment]
DoctrineCacheBundle:

![doctrine-cache-deprecation](https://user-images.githubusercontent.com/73419/46531663-53232400-c89e-11e8-90a5-98340fb8ab60.png)

**Comment by javiereguiluz** [comment]
Closing this in favor of: https://github.com/doctrine/DoctrineCacheBundle/pull/143
