### ISSUE TITLE
Deprecations after upgrading to Symfony 4.2 beta1

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#888]
They are all caused by Doctrine bundles. What can we do to solve them before Symfony 4.2 release? Thanks!

![deprecations](https://user-images.githubusercontent.com/73419/48053668-8a416980-e1ab-11e8-983a-9a4e071aef94.png)

**Comment by dmaicher** [comment]
Most should be fixed now I think :blush: 

See https://github.com/symfony/demo/pull/912.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because I cannot see deprecation messages any longer.
