### ISSUE TITLE
Translation broke after upgrading to Symfony 4.2 beta1

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#889]
Translated messages using the new format no longer work:

![i18n-error](https://user-images.githubusercontent.com/73419/48053722-ae9d4600-e1ab-11e8-9e25-0faf84a975e4.png)

This is probably because we need to add the suffix in the translation messages to enable the new format explicitly.

**Comment by ogizanagi** [comment]
I think you just need to rename translations files with the `+intl-icu` suffix:

```diff
- messages.en.xlf
+ messages+intl-icu.en.xlf
```

(https://github.com/symfony/symfony/pull/28952)

**Comment by gmsantos** [comment]
@javiereguiluz I will work on that

**Comment by javiereguiluz** [comment]
@gmsantos great! Thanks a lot.

**Comment by javiereguiluz** [comment]
Fixed by #890.
