### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#900]
when run composer update:

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in /usr/share/php/Composer/DependencyResolver/Solver.php on line 220

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

it was working before

**Comment by KirbyFox** [comment]
@lxregistry Try the following:

php -d memory_limit=-1 /usr/local/bin/composer update

**Comment by lxregistry** [comment]
with -1 it consume all memory
