### ISSUE TITLE
Replace QueryBuilder by DQL?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#917]
According to [this comment](https://www.reddit.com/r/PHP/comments/a58yt9/phpstorm_doctrine_query_language_support/eblvfmd/) from @ocramius, using DQL inside a NOWDOC string is recommended vs. using the query builder. In fact, he says that *"query builder is less safe and less readable"*.

Given that he's one of the leaders of Doctrine ... should we consider this a "Doctrine best-practice" and change the queries of our repositories?

**Comment by Ocramius** [comment]
If you don't have dynamic DQL/SQL, a string will be one layer of indirection less, plus some wins in readability and static analysis (for tools that support it)

**Comment by yceruto** [comment]
I think that's convenient for simple queries, but what about dinamic DQL?:
https://github.com/symfony/demo/blob/bbe1e498ad557a8d773e0f27a7b06cfa23ed4917/src/Repository/PostRepository.php#L78-L91

What would be the version in DQL that improves readability versus QueryBuilder?

**Comment by yceruto** [comment]
Looking at the code, I don't see any query where this would apply.

**Comment by Ocramius** [comment]
Dynamic DQL can (and probably should) stick with the `QueryBuilder`

**Comment by stof** [comment]
> query builder is less safe and less readable

AFAIU, the `less safe` part here was referring to being safe in regards to refactoring, once PHPStorm support DQL strings (as it can refactor them).
I don't think it is related at all to security (as the QueryBuilder produces DQL anyway).

**Comment by Ocramius** [comment]
"safe" as in "type-safe"

**Comment by stof** [comment]
is it actually *less* type-safe ? Any validation running on the DQL query will also run when it was created with a QueryBuilder.

**Comment by Ocramius** [comment]
I'm more interested in inspecting it *before* running it. If tooling starts
to parse DQL snippets upfront (think PHPStan plugins), looking for class
references, property types and so on, you can infer type information before
touching the runtime.

**Comment by javiereguiluz** [comment]
Closing this because it's not applicable to this project because of how our queries look. But for other projects this idea still applies 👍  Thank you all for the discussion!
