### ISSUE TITLE
Demo installation error

### ISSUE THREAD

**Issue by 1988gadocansey** [symfony/demo#922]
MacOS php7.2  [RuntimeException]                   
  The "--demo" option does not exist.

**Comment by javiereguiluz** [comment]
I've just tested this and it worked for me:

```bash
$ symfony new --demo my_project
```

Please, make sure to install the latest "Symfony Client" version downloaded from https://symfony.com/download

I'm closing this as "fixed" but if the problem persist, please tell us so we can reopen it. Thanks!

**Comment by medre** [comment]
You need to update your current cli version and set the symfony cli PATH with export command.
`export PATH="$HOME/.symfony/bin:$PATH"`
