### ISSUE TITLE
Opening any post throws Exception

### ISSUE THREAD

**Issue by Matvien** [symfony/demo#932]
I open http://127.0.0.1:8000/ru/blog/ and then when I try to click on any post header, I get the Exception.

![image](https://user-images.githubusercontent.com/31967380/51252368-77be8a00-19bd-11e9-8904-fc79f6bc8fd0.png)

**Comment by yceruto** [comment]
Confirmed and fixing in https://github.com/symfony/demo/pull/933

Btw, the error message is quite confusing.
