### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by azianfr** [symfony/demo#940]
Hello,

there is a missing translation for the key `menu.search` in some locales

[▼
  "id" => "menu.search"
  "domain" => "messages"
  "locale" => "fr"
]

**Comment by javiereguiluz** [comment]
@azianfr thanks for reporting this issue. It looks like we have this translation for the French locale. See https://github.com/symfony/demo/blob/0a99a78135cca23635761c4952d23e04c1130c00/translations/messages%2Bintl-icu.fr.xlf#L298

So, could you please share a screenshot of the web debug toolbar or the profiler showing this missing translation to see if we can debug this problem? Thanks.

**Comment by javiereguiluz** [comment]
I'm closing here because of the lack of feedback. Hopefully this was solved. Thanks.
