### ISSUE TITLE
Flash messages don't work

### ISSUE THREAD

**Issue by Carrancio** [symfony/demo#945]
Previous versions worked fine, I don't know when it stopped working.

**Comment by ker0x** [comment]
Hello @Carrancio,

Are you noticing the bug on the `1.3.3` version or on the `master` branch ? Because i just tried on it with dependencies up-to-date and everything work fine.

**Comment by Carrancio** [comment]
Ok. I followed the steps on the README and it installs the 1.3.3 version, the master branch works fine, should I close the issue?

**Comment by ker0x** [comment]
I will let @javiereguiluz decided, but i think we can let it open until `1.3.4` is released !

**Comment by javiereguiluz** [comment]
1.3.4 version has just been tagged: https://github.com/symfony/demo/releases/tag/v1.3.4

I'm closing this as fixed, but please reopen if this still doesn't work. Thanks.
