### ISSUE TITLE
use Voter constants instead of plain explicit string

### ISSUE THREAD

**Issue by inmarelibero** [symfony/demo#946]
using `PostVoter::SHOW` instead of `'show'` is preferable in https://github.com/symfony/demo/blob/master/src/Controller/Admin/BlogController.php#L122

so, 
` $this->denyAccessUnlessGranted(PostVoter::SHOW, $post, 'Posts can only be shown to their authors.');`
instead of 
` $this->denyAccessUnlessGranted('show', $post, 'Posts can only be shown to their authors.');`

I can produce a PR if needed

**Comment by javiereguiluz** [comment]
I think we should do this change. In PHP code using these classes is easy and the resulting code is concise. It's not the same for the Twig templates, but we don't have to change this in the, (if any of the templates uses it in `is_granted()`).

Thanks for your proposal @inmarelibero!

**Comment by inmarelibero** [comment]
PR was sent https://github.com/symfony/demo/pull/948/files

waiting for feedbacks/review

**Comment by javiereguiluz** [comment]
Closing as fixed by #948.
