### ISSUE TITLE
[RFC] Add links to prev and next blog Post

### ISSUE THREAD

**Issue by inmarelibero** [symfony/demo#950]
The proposal is to add one of the most classic features: `prev` and `next` links in the page of a single Post

![screenshot-127 0 0 1-8000-2019 02 21-12-53-48](https://user-images.githubusercontent.com/254808/53167373-05eae900-35d8-11e9-84f9-ab1b75c66653.png)

Useful for:
 - showing how queries can be implemented for this feature
 - add a couple of tests

**Comment by javiereguiluz** [comment]
I've been thinking about this ... and I prefer to close this as "won't fix". I don't see much gain from implementing this feature. This Demo app is about showing Symfony features, not implementing a real blog engine ... so let's not implement this. In any case, thanks a lot for your proposal!
