### ISSUE TITLE
HTTP 500 Internal Server Error 

### ISSUE THREAD

**Issue by maximsamoilov** [symfony/demo#956]
Installed through composer 
PHP 7.1.2
Symfony 4.2.4
route /en/blog/

Argument 1 passed to App\Twig\SourceCodeExtension::getTemplateSource() must be an instance of Twig\Template, instance of Twig\TemplateWrapper given, called in /Applications/MAMP/htdocs/sf4demo.local/src/Twig/SourceCodeExtension.php on line 51

**Comment by omatamix** [comment]
I get the same issue. After composer update i get that error.

**Comment by nbsoftware** [comment]
I confirm, same error here after composer update.

**Comment by nbsoftware** [comment]
Workaround found here: https://github.com/bobdenotter/demo/commit/1f60707116b7a5f39479d219dbfaaf5c354afa62

**Comment by maximsamoilov** [comment]
> 
> 
> Workaround found here: [bobdenotter@1f60707](https://github.com/bobdenotter/demo/commit/1f60707116b7a5f39479d219dbfaaf5c354afa62)

thanks! it works

**Comment by javiereguiluz** [comment]
Closing as fixed by #955. Thanks!
