### ISSUE TITLE
If set ENV_APP=prod - nothing changes

### ISSUE THREAD

**Issue by nickicool** [symfony/demo#965]
If set ENV_APP=prod (in .env) - nothing changes, Symfony still in dev mode! Previously (I remember in Symfony 4.1), this was enough to change modes dev/prod. Why isn't it working now? Cache was cleaning.

Windows 7
Symfony 4.2.4 DemoApp (08.04.2019)

**Comment by bocharsky-bw** [comment]
Hm, I can't reproduce it. For me it works - I checked both `symfony serve` and `bin/console server:run`, I even don't clear the cache. But I'm on Mac

**Comment by nickicool** [comment]
... sorry! I find problem in PHPStorm - save settings will broken! Very unexpected bug...
