### ISSUE TITLE
Tag icon after updating to FontAwesome 5.8

### ISSUE THREAD

**Issue by Carrancio** [symfony/demo#970]
It looks that the new update to FontAwesome 5.8 has broken the tag icon.

![image](https://user-images.githubusercontent.com/23532694/57201403-d6be0400-6f98-11e9-91eb-c171f254f8d5.png)

**Comment by bocharsky-bw** [comment]
Fixed in #971, could you double check it works for you in that branch?

**Comment by Carrancio** [comment]
It does work fine, thanks @bocharsky-bw

**Comment by bocharsky-bw** [comment]
Thank you for the feedback!
