### ISSUE TITLE
Update the way events are used

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#975]
After #974 is merged, we should refactor the way we use events as explained in https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

In practice, we should:

* Remove the `src/Events.php` and use event objects instead of event names
* Create a new event object to replace the GenericEvent used in BlogController
* Update the calls to dispatch() to remove the event name

**Comment by ayshiff** [comment]
I would like to work on it 👍

**Comment by javiereguiluz** [comment]
Fixed by #977.
