### ISSUE TITLE
No assets are built on installation and there are no instructions for this

### ISSUE THREAD

**Issue by ostrolucky** [symfony/demo#980]
Doing what's currently in README.md is enough for running the page, but it doesn't install any assets, so page is completely without any css.

**Comment by kartikpatelp** [comment]
Is there any way to install assets after installation ?

**Comment by ostrolucky** [comment]
`npm install && npm run-script build`

**Comment by bocharsky-bw** [comment]
Confirm, that's the problem we have currently, I fixed it in #982
