### ISSUE TITLE
Default project css file not found

### ISSUE THREAD

**Issue by vladviolenty** [symfony/demo#988]
File app.b82aa2d9.css not found at symfony 4.3.0
![image](https://user-images.githubusercontent.com/10224008/58796443-f5e69a80-8605-11e9-9063-5f41c95592af.png)

**Comment by bocharsky-bw** [comment]
Looks like a duplicate of #980

**Comment by javiereguiluz** [comment]
Yes, we're closing it as a duplicate of #980. @vladviolenty thanks for reporting!
