### ISSUE TITLE
SYMFONY_PHPUNIT_VERSION in the phpunit.xml.dist has no effect

### ISSUE THREAD

**Issue by tristanbes** [symfony/demo#992]
Hello,

It seems that `<env name="SYMFONY_PHPUNIT_VERSION" value="7.1"/>` contained in the [phpunit.xml.dist](https://github.com/symfony/demo/blob/master/phpunit.xml.dist#L15) has literally no effect on the PHPUnit version used instead of the version `7.1`

Let's see for yourself on your Travis builds: https://travis-ci.org/symfony/demo/jobs/540800942#L637 where version `6.5.14` is used.

[Commenting those 3 lines seems to fix this problem](https://github.com/symfony/demo/blob/master/bin/phpunit#L11-L13), reading the value from phpunit.xml.dist again.

--- 

Thanks @Kocal to help me tracking this down.

**Comment by mbabker** [comment]
The `bin/phpunit` file (and probably `phpunit.xml.dist`) should be updated for the PHPUnit bridge changes in SF 4.3, which includes removing the lines you've highlighted.  But, that's probably blocked right now by #998.

**Comment by dmaicher** [comment]
@javiereguiluz so this one can also be closed? :wink: Was fixed by https://github.com/symfony/demo/pull/1000

**Comment by javiereguiluz** [comment]
Yes, closing as as fixed. Thanks!
