### ISSUE TITLE
Fix Travis failing tests

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/demo#998]
This is our Travis CI test suite now:

![image](https://user-images.githubusercontent.com/73419/59186893-50d34100-8b74-11e9-98ab-20b41c129185.png)

The failing tests look like this:

![image](https://user-images.githubusercontent.com/73419/59186908-5c266c80-8b74-11e9-87c1-2b6d7e4fc83e.png)

Full details: https://travis-ci.org/symfony/demo/jobs/543634635

This is NOT related to #997. It was failing way before. Anyone can help us fix this? Thanks!

**Comment by dmaicher** [comment]
Currently looking into this. Can reproduce it locally using php 7.1.30

**Comment by dmaicher** [comment]
@javiereguiluz fixed in https://github.com/symfony/demo/pull/1001
